### ISSUE TITLE
OPC/OpenXML document Manifest+SignatureProperties signed

### ISSUE THREAD

**Issue by hvisage** [XML-Security/signxml#101]
Good day,

 I'm hitting my head against a wall with the following "fun":

The example OPC/OPenXML .psdsxs file given to us, have the following format:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<Signature xmlns="http://www.w3.org/2000/09/xmldsig#" Id="SignatureIdValue">
  <SignedInfo>
    <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
    <SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
    <Reference URI="#idPackageObject" Type="http://www.w3.org/2000/09/xmldsig#Object">
      <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
      <DigestValue>...</DigestValue>
    </Reference>
  </SignedInfo>
  <SignatureValue>...</SignatureValue>
  <KeyInfo>..<KeyInfo>
  <Object Id="idPackageObject">
    <Manifest>
      <Reference URI="/0c906836-62ac-407c-bbc8-df1aede3352a?ContentType=application/xml">
        <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
        <DigestValue>UJgNeHvKzchbJ/I58NcGdd9YhlI=</DigestValue>
      </Reference>
    </Manifest>
    <SignatureProperties>
      <SignatureProperty Id="idSignatureTime" Target="#SignatureIdValue">
        <SignatureTime xmlns="http://schemas.openxmlformats.org/package/2006/digital-signature">
          <Format>YYYY-MM-DDThh:mm:ss.sTZD</Format>
          <Value>2017-09-21T15:02:31.2+02:00</Value>
        </SignatureTime>
      </SignatureProperty>
    </SignatureProperties>
  </Object>
</Signature>
```

Using the Enveloping method with Elementtree (After I've constructed initially the <Manifest> using the minidom) I can add the `<Manifest>` that is encapsulated in an `<Object>` and signed. How ever, I suspect that `<SignatureProperties>` are used by the Microsoft OPC (Open Package Convention) given the `Target="#SignatureValue"`

Passing the `<Manifest>` and `<SignatureProperties>` as `toxml()` strings, causes the XMLSigner to encode it to be a valid XML string.

In essence I want to say to XMLSigner: "HEre is the <Object> to sign, using the enveloping method, but don't envelop it inside an Object"

**Comment by kislyuk** [comment]
Sorry, you need to be clearer about what you need here.
