### ISSUE TITLE
Initializer for ctype 'char[]' must be a bytes or list or tuple, not str

### ISSUE THREAD

**Issue by harmonik001** [XML-Security/signxml#105]
Hello,

I try to sing up XML file with signxml library. I extract certificate (publicCert.pem) and privatekey (privateKey.pem) from .p12 file over openssl. 

The sample code:
****
from signxml import XMLSigner
import xml.etree.ElementTree as ET

cert = open("publicCert.pem").read()
key = open("privateKey.pem").read()
data_to_sign = open("data.xml").read()
root = ET.fromstring(data_to_sign)
signed_root = XMLSigner().sign(root, key=key, cert=cert)
****
Give me the error: Initializer for ctype 'char[]' must be a bytes or list or tuple, not str. 

I am so sorry for basic ignorance of the problem, but I am a newcomer in this area. I will be very grateful for every advice.

Martin

**Comment by nomadmtb** [comment]
Is still an issue for you @harmonik001 ?  I was getting this error if I tried supplying the key, cert to the XMLSigner.sign() method as a string.  If you read the file as bytes I think it should do the trick. open("publicCert.pem", "rb")

**Comment by mcondarelli** [comment]
I was bitten by this, also.

either:

    cert = open("example.pem").read().encode()

or

    cert = open("example.pem", "rb").read()

will work, but I strongly suggest to update documentation.

**Comment by anterof5** [comment]
> I was bitten by this, also.
> 
> either:
> 
> ```
> cert = open("example.pem").read().encode()
> ```
> or
> 
> ```
> cert = open("example.pem", "rb").read()
> ```
> will work, but I strongly suggest to update documentation.

Hi friends, i used both solutions, but now i have a wrong signature in my xml :( 

My full traceback is:

```
Traceback (most recent call last):
  File "/home/antero/miniconda3/lib/python3.7/site-packages/signxml/util/__init__.py", line 197, in _add_cert_to_store
    X509StoreContext(store, cert).verify_certificate()
  File "/home/antero/miniconda3/lib/python3.7/site-packages/OpenSSL/crypto.py", line 1797, in verify_certificate
    raise self._exception_from_context()
OpenSSL.crypto.X509StoreContextError: [20, 0, 'unable to get local issuer certificate']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "assinar.py", line 11, in <module>
    verified_data = XMLVerifier().verify(signed_root).signed_xml
  File "/home/antero/miniconda3/lib/python3.7/site-packages/signxml/__init__.py", line 718, in verify
    signing_cert = verify_x509_cert_chain(cert_chain, ca_pem_file=ca_pem_file, ca_path=ca_path)
  File "/home/antero/miniconda3/lib/python3.7/site-packages/signxml/util/__init__.py", line 241, in verify_x509_cert_chain
    raise last_error
  File "/home/antero/miniconda3/lib/python3.7/site-packages/signxml/util/__init__.py", line 230, in verify_x509_cert_chain
    end_of_chain = _add_cert_to_store(store, cert)
  File "/home/antero/miniconda3/lib/python3.7/site-packages/signxml/util/__init__.py", line 199, in _add_cert_to_store
    raise InvalidCertificate(e)
signxml.exceptions.InvalidCertificate: [20, 0, 'unable to get local issuer certificate']
```

And my code:

```
from signxml import XMLSigner, XMLVerifier
import xml.etree.ElementTree as ET

cert = open("example.pem", "rb").read()
key = open("example.key","rb").read()

data_to_sign = open("example.xml").read()
root = ET.fromstring(data_to_sign)

signed_root = XMLSigner().sign(root, key=key, cert=cert)
verified_data = XMLVerifier().verify(signed_root).signed_xml
```

**Comment by kislyuk** [comment]
Addressed the bytes vs. string issue for keys in cfc566d4ad29106337d0d29ea8022daa607455c4. The certificate was already accepted as either bytes or string.

Your most recent issue is due to not configuring the verification procedure correctly to use your self-signed cert. Added documentation in the synopsis on how to properly do that.
