### ISSUE TITLE
Deprecation Warning

### ISSUE THREAD

**Issue by ensarman** [XML-Security/signxml#108]
I get a warning when I use XMLsinger :1234: 

CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(padding=PKCS1v15(), algorithm=hash_alg)

Have it fixed or not yet?

**Comment by mcondarelli** [comment]
Same problem here.

**Comment by ragerin** [comment]
Same here.

```python
site-packages\signxml\__init__.py:370: CryptographyDeprecationWarning: signer and verifier have been deprecated. Please use sign and verify instead.
  signer = key.signer(padding=PKCS1v15(), algorithm=hash_alg)
```
