### ISSUE TITLE
PEM header not stripped from OpenSSL.crypto.X509 cert

### ISSUE THREAD

**Issue by bobdoah** [XML-Security/signxml#111]
if an `OpenSSL.crypto.X509` cert object is passed into sign, the `OpenSSL.crypto.dump_certificate` method is used to populate the `X509Certificate` element:

```python
if isinstance(cert, (str, bytes)):
    x509_certificate.text = strip_pem_header(cert)
else:
    from OpenSSL.crypto import dump_certificate, FILETYPE_PEM
    x509_certificate.text = dump_certificate(FILETYPE_PEM, cert)
```

The dump_certificate method does not strip the `-----BEGIN CERTIFICATE-----` and `-----END CERTIFICATE-----` from the certificate:

```python
In [9]: crypto.dump_certificate(crypto.FILETYPE_PEM, p12.get_certificate())
Out[9]: b'-----BEGIN CERTIFICATE-----\nMIIFPTCCBCWgAwIBAgIQPtZTFRExYZeVJMcBKDDKeDANBgkqhkiG9w0BAQUFADCB\ntDELMAkGA1UEBhMCVVMxFzAVBgNVBAoT
```
When I attempt to validate the signed xml generated, lxml raises this exception:
```

DocumentInvalid: Element '{http://www.w3.org/2000/09/xmldsig#}X509Certificate': '-----BEGIN CERTIFICATE-----
MIIFPTCCBCWgAwIBAgIQPtZTFRExYZeVJMcBKDDKeDANBgkqhkiG9w0BAQUFADCB

...

ng==
-----END CERTIFICATE-----
' is not a valid value of the atomic type 'xs:base64Binary'., line 1
```

**Comment by kislyuk** [comment]
This was fixed in https://github.com/XML-Security/signxml/commit/4e5bf2c7441828aac2a290f83a84b6ab9156dddc, right?

I just finally rolled a release with this change (v2.6.0), sorry about the delay. Please reopen if you still observe the problem.
