### ISSUE TITLE
default c14n_algorithm is outdated.

### ISSUE THREAD

**Issue by anishchadayappan** [XML-Security/signxml#114]
when XMLSigner is used for signing the assertion, AWS rejects the assertion when c14n_algorith = 'http://www.w3.org/2006/12/xml-c14n11' is used which is the default.

when we changed the default c14n_algorith = 'http://www.w3.org/2001/10/xml-exc-c14n#'  it worked.

When we visite the site: http://www.w3.org/2001/10/xml-exc-c14n#
![screen shot 2018-06-04 at 12 17 26 pm](https://user-images.githubusercontent.com/7627313/40902332-4f6944ce-67f1-11e8-858e-df8d28f5301c.png)
and hence the rejection by AWS.

Please fix it asap.

**Comment by kislyuk** [comment]
Closing as invalid. You can help by providing clear and specific instructions on how to reproduce the issue that you see.
