### ISSUE TITLE
Wont replace <Signature> in SOAP XML just appends or inserts

### ISSUE THREAD

**Issue by paultargett** [XML-Security/signxml#115]
Hi, I'm using this library to create a signature for a SOAP message. I'm including a `<Signature Id="placeholder"/>` in the XML but I can not get the library to insert using the `<Signature>` element.

Element insert code:
```

    Signature = ElementTree.SubElement(security, "Signature")
    Signature.set("Id","placeholder")
```
Sign generation, root is an ElemenTree XML structure:

```
    xmlsign = XMLSigner(method=signxml.methods.enveloped,
                       signature_algorithm="rsa-sha1",
                       digest_algorithm="sha1",
                       c14n_algorithm="http://www.w3.org/2001/10/xml-exc-c14n#")

    signed_root = xmlsign.sign(data=root,
                              key=privatekey,
                              cert=publickey,
                              reference_uri="#Timestamp-1")

    signed_root.set("xmlns","http://www.w3.org/2000/09/xmldsig#")
```

When I look through what's happening the library appears to be unable to find the <SIgnature> element in the ElementTree XML.

**Comment by kislyuk** [comment]
Hi, sorry about the delay in my response.

Are you sure that your `Signature` node is in the correct namespace? It *must* be in the "http://www.w3.org/2000/09/xmldsig#" namespace. You can check the namespace of the node by dumping your XML into a string. If the node is not in the correct namespace, it won't be found and used as a placeholder.

**Comment by kislyuk** [comment]
Closing due to lack of response.
