### ISSUE TITLE
Publish new version ?

### ISSUE THREAD

**Issue by danimaribeiro** [XML-Security/signxml#120]
Could you publish a new version to fix deprecationwarnings? https://github.com/XML-Security/signxml/commit/208e85c40327de454107f969440b1b8be1bbb64f

**Comment by DaOneTwo** [comment]
I would really love to see this released as well.  Soon I will have to resort to a fork model.   If there is anywhere a relative OS noob could help you out please let me know!

**Comment by kislyuk** [comment]
Released in v2.6.0. Sorry about the delay.
