### ISSUE TITLE
Sign with engine_pkcs11

### ISSUE THREAD

**Issue by edsonitk** [XML-Security/signxml#123]
Hi
Would it be possible to sign documents with signxml by passing in signxml.XMLSigner (), the key as an engine_pkcs11 obejto or a primitive key coming from pykcs11?

**Comment by kislyuk** [comment]
Hello! I don't plan on working on this, and I will only accept a PR that uses the cryptography backend API to interface with a PKCS11 backend library. But you are very welcome to try your hand at this, and open a PR when you feel ready. 😄

**Comment by kislyuk** [comment]
Closing due to lack of response.
