### ISSUE TITLE
NetIQ SAML NMAS compatibility

### ISSUE THREAD

**Issue by lhoekenga** [XML-Security/signxml#127]
We're trying to sign SAML 1.0 assertions for use with NetIQ's (Microfocus's) SAML SASL mechanism.  Their implementation is outdated (SAML 1.0 only, requires SHA1 signatures) and problematic.  It's complaining about signature validation.

I believe the issue is that (save for the line breaks included in the x509 certificate) the entire Signature element is on a single line.  If I sign the same document using [xmlsectool](https://wiki.shibboleth.net/confluence/display/XSTJ2/xmlsectool+V2+Home),  the signature value and modulus are line wrapped, and each element is on it's own line.

The SASL mechanism accepts the document signed by xmlsectool and rejects the document signed by signxml.

Is it possible to replicate the xmlsectool behavior using signxml?

**Comment by kislyuk** [comment]
Thanks for reporting. Whitespace should not matter in signature validation. I have no access to this other library, is it available for integration testing online? I would encourage you to provide a complete example here, or to experiment with the source code of this package to remove line breaks while building the signature, to see if this resolves your problem.

**Comment by kislyuk** [comment]
Closing due to lack of response.
