### ISSUE TITLE
Verifying an AuthnRequest signature passed in URL parameters.

### ISSUE THREAD

**Issue by kaorihinata** [XML-Security/signxml#129]
Hi,

I've been trying to figure out the right way to verify the signature of what I believe is an enveloped signature being passed in a URL instead of in a proper Signature element. In this case, the SAML service provider is passing the signature data in the Signature, SigAlg and SAMLRequest URL parameters. To validate this message would I need to construct a Signature element using that data and insert it into the document before I would be able to validate it with XMLVerifier.verify? Or is there something in the API I'm missing?

Thanks,
Thomas

**Comment by kislyuk** [comment]
This does not sound like an issue with this library, but a question about an implementation-specific use of the SAML spec. See https://docs.oasis-open.org/security/saml/Post2.0/sstc-saml-binding-simplesign.html for more information.

**Comment by kaorihinata** [comment]
Not an issue with the library, as much as I wasn't sure if signxml supported the type of signature I was attempting to generate. I wasn't sure at the time whether or not the external signing method that SAML uses for POST payloads was actually standard, or something nailed on for convenience. If it was an actual, standard method of externally signing XML then I wanted to know how I could achieve it using using signxml as I didn't want to rewrite something if it already existed.

After a bit more research I found that very article and wrote something myself since, as the documentation says, you're just signing a blob. No canonicalization or anything.

**Comment by kislyuk** [comment]
Got it, thanks for the explanation. If you see a good place to tack this information onto the existing documentation for this library, please let me know.

**Comment by kaorihinata** [comment]
Under "Verifying SAML assertions" would work, though that section has quite a few notes already. Following the method described in the OASIS docs above to build the input string, then signing/verifying with `cryptography` is all that's required (which is convenient as `signxml` pulls `cryptography` in as a dependency). The only caveat is that you need to specify PKCS1 v1.5 (`cryptography.hazmat.primitives.asymmetric.padding.PKCS1v15`) for the padding parameter when required.
