### ISSUE TITLE
Relax unnecessary dependency constraints

### ISSUE THREAD

**Issue by nbastin** [XML-Security/signxml#134]
There are a lot of very specific version windows in `setup.py`, some of which span fewer than 9 months of released versions of tools, and create a situation where it's increasingly hard to satisfy them in larger systems.

Specifically, `signxml` works fine with versions of cryptography that pre-date 2.1.4 (which only added an unused dummy symbol), but arbitrarily prevents users from using them.  Is there any reason to have moved the minimum version from 1.8, where it was before?  Similarly with `lxml`, etc?

The commit in question is https://github.com/XML-Security/signxml/commit/439ea916662a5ab215a9b0ee5b2a2f664dba7281 and unfortunately doesn't provide any rationale for the change.

**Comment by kislyuk** [comment]
Thanks for the comment. The commit does provide a rationale: the dependencies are set to match those included as APT packages in Ubuntu 18.04.

I'd advise using the release of signxml before this commit. Do you have a specific setup in which you are unable to update your dependencies?

**Comment by kislyuk** [comment]
To provide a fuller rationale: supporting wider version ranges requires testing, and this package does not currently have a test suite that tests it against older versions of its dependencies. In the absence of such testing, I choose to support only those dependency versions which are expected to be well-supported upstream, such as those bracketed by LTS operating system releases.

If you are interested in support for other dependency versions, you are welcome to submit a PR which would implement a test suite over the full range of dependency versions.
