### ISSUE TITLE
Error: TypeError: from_buffer() cannot return the address of a unicode object

### ISSUE THREAD

**Issue by marcosstefani** [XML-Security/signxml#135]
Hi, I have the following files:

certificate.py:
```
import os
import xml.etree.ElementTree as ET
from OpenSSL.crypto import *
from signxml import XMLSigner, XMLVerifier, methods

CERT_FOLDER = './certificates'

class Certificate:
    
    def __init__(self, cnpj):
        self.cnpj = cnpj
        
    def _folder(self):
        folder = '{}/{}'.format(CERT_FOLDER, self.cnpj)
        if (not os.path.exists(folder)):
            os.mkdir(folder)
        return folder;
        
    def _existsFile(self):
        folder = self._folder()
        return os.path.isfile('{}/{}/chave.pem.'.format(folder, self.cnpj))

    def _createFiles(self, passwd):
        folder = self._folder()
        p12 = load_pkcs12(open('{}/{}.pfx'.format(CERT_FOLDER, self.cnpj), 'rb').read(), passwd)

        pkey = p12.get_privatekey()
        open('{}/chave.pem'.format(folder), 'wb').write(dump_privatekey(FILETYPE_PEM, pkey))

        cert = p12.get_certificate()
        open('{}/certificado.pem'.format(folder), 'wb').write(dump_certificate(FILETYPE_PEM, cert))

        ca_certs = p12.get_ca_certificates()
        ca_file = open('{}/ca.pem'.format(folder), 'wb')
        for ca in ca_certs:
            ca_file.write(dump_certificate(FILETYPE_PEM, ca))

    def build(self, passwd):
        if (not self._existsFile()):
            self._createFiles(passwd)
            
    def signXML(self, xml):
        folder = self._folder()
        cert = open('{}/certificado.pem'.format(folder)).read()
        key = open('{}/chave.pem'.format(folder)).read()
        root = ET.fromstring(xml)
        signed_root = XMLSigner(method=methods.enveloped, digest_algorithm='sha1').sign(root, key=key, cert=cert)
        print(signed_root)
        return ET.tostring(signed_root, encoding='utf8', method='xml')
```

app.py:
```
from certificate import Certificate

cnpj = 'number_id'
senha = 'pass'

cert = Certificate(cnpj)
cert.build(senha)

xml = "<note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't forget me this weekend!</body></note>"
signedXML = cert.signXML(xml)
print(signedXML)
```

but I have the following traceback:
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    signedXML = cert.signXML(xml)
  File "/home/marcos/Projects/taruira/certificate.py", line 47, in signXML
    signed_root = XMLSigner(method=methods.enveloped, digest_algorithm='sha1').sign(root, key=key, cert=cert)
  File "/home/marcos/env/lib/python3.6/site-packages/signxml/__init__.py", line 362, in sign
    key = load_pem_private_key(key, password=passphrase, backend=default_backend())
  File "/home/marcos/env/lib/python3.6/site-packages/cryptography/hazmat/primitives/serialization/base.py", line 16, in load_pem_private_key
    return backend.load_pem_private_key(data, password)
  File "/home/marcos/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1051, in load_pem_private_key
    password,
  File "/home/marcos/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 1244, in _load_key
    mem_bio = self._bytes_to_bio(data)
  File "/home/marcos/env/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 468, in _bytes_to_bio
    data_ptr = self._ffi.from_buffer(data)
TypeError: from_buffer() cannot return the address of a unicode object

**Comment by NorakGithub** [comment]
@marcosstefani Hello there, did you find any solution to this?

**Comment by tarlanpayment** [comment]
I just used incorrect public or private key. After using right error disappeared

**Comment by kislyuk** [comment]
Nothing to be done here.
