### ISSUE TITLE
signxml incorrectly omits Transforms from detached signature with references

### ISSUE THREAD

**Issue by nimish** [XML-Security/signxml#136]
The spec allows for different c14n methods for the ds:SignedInfo (specified as c14n) and the ds:Reference elements. signxml, for enveloped signatures only, correctly generates this list of transforms, although it limits the c14n algo to the one used for ds:SignedInfo.

These must be included with all types of signatures. signxml should not assume that the SignedInfo c14n method and the reference c14n method are the same, and it can't omit the list of transforms.

xmlsec will fail to verify a detached signature without the list of transforms.

**Comment by kislyuk** [comment]
In order to proceed with addressing this issue, can you help me by creating a test case that is expected to succeed, but fails?

**Comment by nimish** [comment]
@kislyuk See https://github.com/XML-Security/signxml/pull/107, basically any use of the code that generates a detached signature with a reference to some other element will be missing the c14n method in the SignedInfo.

@kislyuk Hard to give a working example w/o leaking keys, but:


    detached_signer = signxml.XMLSigner(
        method=signxml.methods.detached,
        c14n_algorithm=xml_c14n_algo, # choose something here, say exc-c14n
    )

    sig = detached_signer.sign(timestamp, cert=cert, key=key) # timestamp is just an element
    sig.xpath("//ds:Transforms", namespaces=nsmap)[0] # fails! empty list

Should be equal to, e.g. (depending on your choice of c14n algo): 
`<ds:Transforms xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms>`

**Comment by kislyuk** [comment]
@nimish I merged #107 and added a test. I don't see a use case for having different c14n algorithms for the signature vs. the reference. Can you give an example of a practical application that requires it?

**Comment by kislyuk** [comment]
(I guess that is essentially the same question I asked in https://github.com/XML-Security/signxml/issues/137)

**Comment by nimish** [comment]
@kislyuk I ended up closing that since I think I confused myself about what the actual thing I needed was. If I can dig up a simple reproducer I'll re-open it but for now just fixing the detached reference c14n thing is enough.

**Comment by kislyuk** [comment]
Released in v2.7.0, please test.

**Comment by nimish** [comment]
Appears to work! Thanks
