### ISSUE TITLE
signxml does not distinguish SignedInfo c14n method from Reference transforms

### ISSUE THREAD

**Issue by nimish** [XML-Security/signxml#137]
Related to #136 

XMLDSig distinguishes between the c14n method applied to the SignedInfo element, and the transforms applied to the Referenced elements (which include c14n methods).

signxml only uses one, which is fine for generating signatures but not for verifying them.

xmlsec implements this distinction.

**Comment by kislyuk** [comment]
In order to proceed with addressing this issue, can you help me by creating a test case that is expected to succeed, but fails?

**Comment by nimish** [comment]
Hmm, i have lost the example I had. I'll reopen this if i can dig it back up.
