### ISSUE TITLE
Support to Google cloud App Engine

### ISSUE THREAD

**Issue by vsgobbi** [XML-Security/signxml#138]
Hello there,
I've trying to use signxml with google cloud applications. I wonder if there is a way to use signxml with Google App Engine standard environment with Python 2.7.

Since Google App Engine does not support extending C libraries, is there a way to sign a xml content using X509 with this lib using GAE? 

Best regards, 
Vitor

**Comment by kislyuk** [comment]
Hello,

SignXML requires its dependencies to perform signing, so in order to use it you have to use a host that can accommodate those dependencies.
