### ISSUE TITLE
Error when reading cert and key as string

### ISSUE THREAD

**Issue by myounus96** [XML-Security/signxml#161]
Hi, I am signing the request using example provided in docs, everything is working fine when reading cert and key from files, but when I copy-pasted cert and key files content as string (use case is, I wanna fetch cert and key from db) it showing errors.
**Doing this working fine.**
`cert = open("example.pem").read()`
`key = open("example.key").read()`
**But this gives errors.**
`cert="abc...def"`
`key="ghi..ijk"`

**Doc example(image):**
![image](https://user-images.githubusercontent.com/13608139/93488088-6874aa00-f91f-11ea-8fc3-12220bd01eab.png)

By the way thanks for this simple and awesome library :).

**Comment by myounus96** [comment]
Stacktrace if cert and key both used as strings.
[https://pastebin.pl/view/f7153439](url)

Stacktrace if only cert is string.
[https://pastebin.pl/view/9915f86a](url)

Stacktrace if only key is string.
_The same first one 'ValueError: Could not deserialize key data.' error._

**Comment by kislyuk** [comment]
Your certificate and key serialization formats are incorrect. You have to use a PEM-formatted string. If you want further help, please provide a *complete* reproduction of the issue, including the test certificate and key that you are using.

**Comment by myounus96** [comment]
> Your certificate and key serialization formats are incorrect. You have to use a PEM-formatted string. If you want further help, please provide a _complete_ reproduction of the issue, including the test certificate and key that you are using.

Ok, let me try to find a way to convert a normal string to PEM-formatted and test with that, if I succeed than OK, otherwise I will provide further details.

**Comment by myounus96** [comment]
So I copy paste the pem files content in [this](https://www.gillmeister-software.com/online-tools/text/remove-line-breaks.aspx) tool and put `\n` in `custom text` field, it gives me one line string..and I used that and its working fine.Thank you :)
