### ISSUE TITLE
Ability to select specific standard

### ISSUE THREAD

**Issue by nithinkashyapn** [XML-Security/signxml#162]
Hi,

This is a great library. Is there are way to select the standard needed be it Version 1.1 or Version 2.0? By default the XML output is based on Version 2.0

Thanks

**Comment by kislyuk** [comment]
Thanks - this is not currently supported, but I would love to support it. I have a very limited amount of free time for this project - PRs and sponsorships are welcome.

**Comment by nithinkashyapn** [comment]
Thanks for the reply @kislyuk, will try working on it and raise a PR

**Comment by kislyuk** [comment]
I have decided that XML Signature Version 2.0 (which was never accepted as a W3C standard) will not be supported, so this issue won't be fixed (only 1.1 will be supported).
