### ISSUE TITLE
Update cryptography requirement to atleast 3.2.

### ISSUE THREAD

**Issue by drakonen** [XML-Security/signxml#165]
When running `pip install -r requirements.txt --use-feature=2020-resolver`
The following is displayed.
```
The conflict is caused by:
    The user requested cryptography==3.2.1
    pyopenssl 19.1.0 depends on cryptography>=2.8
    signxml 2.7.2 depends on cryptography<3 and >=2.1.4
```
cryptography < 3.2 a [security issue](https://github.com/advisories/GHSA-hggm-jpg3-v476).

**Comment by kislyuk** [comment]
The issue you describe has been fixed and released in v2.8.1.
