### ISSUE TITLE
How to skip URI validation on sign 

### ISSUE THREAD

**Issue by pascencio** [XML-Security/signxml#166]
Hi,

I have a problem trying to sign a document with an xmlns uri invalid. It's weird because the service provider only receive the signed document with that format.

`lxml.etree.XMLSyntaxError: xmlns: 'http://mi.domain.com MySchema.xsd' is not a valid URI`

Looking for a solution I found this:
https://stackoverflow.com/questions/18692965/how-do-i-skip-validating-the-uri-in-lxml

I had the same problem generating element tree from string and that answer solved my problem.

There is any workaround for this cases?

Thanks in the advance!

**Comment by kislyuk** [comment]
Hi, thanks for your interest. I am not aware of a workaround for this and I'm not entirely sure what specifically you're asking for. Can you provide an example of the input and code you ran, the behavior you expected, and what was produced?

**Comment by pascencio** [comment]
Hi @kislyuk,

I trying to sign a XML but fails because in the XSD import have a invalid URI. In my case that URI is valid for the receiver entity.

**Comment by kislyuk** [comment]
Sorry, I have to close this issue due to insufficient information provided. If you want help with your issue, please follow the instructions above and open a new issue with the information needed.
