### ISSUE TITLE
Signature difference between signxml and xmlsec

### ISSUE THREAD

**Issue by edsonitk** [XML-Security/signxml#171]
Could you help me to find out why the two libraries (signxml and xmlsec) do not sign the same.
The signature accepted by the server is xmlsec.

Code sign signxml:

        signer = XMLSigner(
            method=methods.enveloped,
            signature_algorithm="rsa-sha1",
            digest_algorithm='sha1',
           c14n_algorithm='http://www.w3.org/TR/2001/REC-xml-c14n-20010315')
        ns = {}
        ns[None] = signer.namespaces['ds']
        signer.namespaces = ns

        signed_root = signer.sign(xml_element,
                                  key=self.chave,
                                  cert=self.certificado,
                                  reference_uri=None
                                  )
[signs.zip](https://github.com/XML-Security/signxml/files/6207744/signs.zip)

**Comment by kislyuk** [comment]
Hi, thanks for your interest in SignXML. If you need help, please provide a complete reproduction, including the XML element that was passed as input.

**Comment by alancsouza** [comment]
Same problem here. Do we have any update on the issue?

**Comment by kislyuk** [comment]
There is no update because there was no complete reproduction posted nor an effort made to debug the issue. This library is maintained by volunteers in their spare time; you are welcome to contribute specific knowledge to help resolve the issue that you are facing.

**Comment by kislyuk** [comment]
I am going to close this issue because the original reporter wasn't able to provide the reproduction details necessary to act on the report.

If you have an issue, please post a *complete* reproduction, including the full set of inputs and the expected vs. observed behavior.
