### ISSUE TITLE
[QUESTION] SignXml remove xmlns:ds="http://www.w3.org/2000/09/xmldsig#" while verify

### ISSUE THREAD

**Issue by xalik111** [XML-Security/signxml#172]
Thanks for your library.
Original xml example:
`<ECommerceConnect
	xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
	xmlns:xenc="http://www.w3.org/2001/04/xmlenc#"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://secure.upc.ua/go/pub/schema/xmlpay-1.22.xsd">
	<Message id="123" version="1.0">
		<XMLMPIResponse>
			<MPIResponse>
				<Code>0</Code>
				<MPIEnrolResponse>
					<Enrolled>Y</Enrolled>
					<AcsURL>https://acs-idcheck.acdcproc.com/PaReqMC.jsp</AcsURL>
					<PaReq>eJxVUslugzAQ/ZWIe7ExGOxocESLquZAG7XpoUcEVkBlC0sh/frahCSNLEvzZnnjeWPYTGWx+pFtl9eVb1gmNlaySuo0rw6+8bl/fmDGRsA+a6UMP2QytFJAJLsuPshVnvrGLn6XR8sltj7YdbBtWwRjarmcebbrUMIIMwTsApUnYOkkVCOTALpARdkmWVz1AuLk+Lh9FdRhLmWAFgilbLehcBnlnFNAZwhVXErRZXVjDk1iDjGg2QNJPVR9exIMO4AuAIa2EFnfN2uExnE07+p0DNDtGbtBW53imvJURGEwqnuK9gGJwu8pyjGNfg/0LfzyAekMSONeCoKJhV3MV5ivqbV2XECzH+JSP0KPjdVMZwCN7hEsER347wCldatWcRKcqdAVgZyaupIqQ+l3tSGVXSIyWRS1aqltQLcRnl60rkmvJCPcszzMmTNrO7s0Y670IQ72ZkoNAOkitKwNLStX1t1X+ANTw7nn</PaReq>
					<XID>21060912-938986</XID>
				</MPIEnrolResponse>
			</MPIResponse>
		</XMLMPIResponse>
	</Message>
	<Signature
		xmlns="http://www.w3.org/2000/09/xmldsig#">
		<SignedInfo>
			<CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/>
			<SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
			<Reference URI="">
				<Transforms>
					<Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
				</Transforms>
				<DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
				<DigestValue>zoGFpm99IrtPuZwRdIWDGy2tjPY=</DigestValue>
			</Reference>
		</SignedInfo>
		<SignatureValue>Vce5tTFaQG3Oo7tafJebGxOTeFW8jmiKXDLNipbnES09J8l4HymV71HlaKbVxhdUxjrgXzEX55OR\nKu6ZJZ2lRown6IqkdMf7Hn1tWOMVLoxRwZyj337gZ2frA5qds8EHV6y2UE7H0VLvxinkd1xc7S+G\n6c+XERutpGA6br1Rhqw=</SignatureValue>
	</Signature>
</ECommerceConnect>`

DigestValue from gateway side generating with - xmlns:ds="http://www.w3.org/2000/09/xmldsig#", but when i do `verified_data = signxml.XMLVerifier().verify(xml_response, x509_cert=cert).signed_xml` DigestValue in signxml generate without this.

Xml change at this moment:
`if not c14n_applied and not isinstance(payload, (str, bytes)):
     payload = self._c14n(payload, algorithm=c14n_algorithm)`

After _c14n:
`<ECommerceConnect
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:noNamespaceSchemaLocation="https://secure.upc.ua/go/pub/schema/xmlpay-1.22.xsd">
	<Message id="123" version="1.0">
		<XMLMPIResponse>
			<MPIResponse>
				<Code>0</Code>
				<MPIEnrolResponse>
					<Enrolled>Y</Enrolled>
					<AcsURL>https://acs-idcheck.acdcproc.com/PaReqMC.jsp</AcsURL>
					<PaReq>eJxVUm1vgjAQ/iuG76OlUmjNUeNGlvkBYzb9AQQaYVNAXgb++10RdaZpcs/d9bm75wrL4XSc/eq6ycsisBybWjNdJGWaF4fA2u/eX4S1VLDLaq3DL510tVYQ6aaJD3qWp4G1jT/12fHYHA9nwmVznzHmi7kruOtQX/o+k5aC7QrzFEyVFBayGZAbRMo6yeKiVRAn59f1RnFXeFwAmSCcdL0OlSe4lJIDuUIo4pNWTVZWdlcldhcDGT2QlF3R1hclqAvkBqCrjypr22pBSN/39tM7EwPyaGPbGatBriFPVRSueryXaLdiUfgzRDnlmzBi0fc+AGIyII1brRhlDvWonFG54HzBcIDRD/HJNGHGpjjTFUBlaqymiAn8dwBqXeMqLkoKDN0R6KEqC40ZqN/dhlQ3icr08VhiSWMDeYzw9mF0TVqUjEnf8eeeN/ZxdRnGHPVhLvVHSgOAmEdkWhuZVo7W01f4A0q8ucE=</PaReq>
					<XID>21060912-943625</XID>
				</MPIEnrolResponse>
			</MPIResponse>
		</XMLMPIResponse>
	</Message>
</ECommerceConnect>`

So I get exception signxml.exceptions.InvalidDigest: Digest mismatch for reference 0

**Comment by kislyuk** [comment]
Thanks for your interest in SignXML. Unfortunately there is not enough information in your report to understand what is going wrong. If you need help, please provide a complete reproduction of your problem, including all input data, the complete source code necessary to reproduce how you ran SignXML, the expected output, and the output you saw.

**Comment by xalik111** [comment]
@kislyuk thanks for fast response. my test - `
xml_str = f'<ECommerceConnect xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://secure.upc.ua/go/pub/schema/xmlpay-1.22.xsd"><Message id="123" version="1.0"><XMLMPIResponse><MPIResponse><Code>0</Code><MPIEnrolResponse><Enrolled>Y</Enrolled><AcsURL>https://acs-idcheck.acdcproc.com/PaReqMC.jsp</AcsURL><PaReq>eJxVUttygjAQ/RWG95ILISbOEofW6dQHrK30AxjICDMKyKVqv74JRa0Pmdmzl7O7ZwOL82HvfOu2K+sqdImHXUdXWZ2X1S50v5LXJ+EuFCRFq/Vyq7Oh1Qpi3XXpTjtlHrqb9FMfCac+l8GMUSKYTzmjUhIWCEJmkjMiXQWbyOQpmDop08ijgK7QULZZkVa9gjQ7Pq/WKmCCBwLQBOGg29VScRFIKQNAfxCq9KBVV9SNNzSZN6SARg9k9VD17UUJzABdAQztXhV938wROp1O3kOdjQG6j7EZrNUZrnOZq3gZncy7xElE4+TjEm8xfU8isv6JQkA2A/K014piSjAnzCFi7gdzZlYc/ZAe7BB2bWx2+gPQ2B7RFLGB/w4wWrfmFBclhQndEOhzU1faZBjymw257jJV6P2+Ni2tDei+wsub1TXrjWQ+xoJJTvjMaju6LGNp9KEMy5HSAkC2CE1nQ9PJjfXwFX4BOKq5pw==</PaReq><XID>21061421-690570</XID></MPIEnrolResponse></MPIResponse></XMLMPIResponse></Message><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><Reference URI=""><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><DigestValue>MvvvBp6E13+6pTJCmPLY4udvF/U=</DigestValue></Reference></SignedInfo><SignatureValue>fOAtk5OllrkHuOttfd70QxkBX3xLeV4Ivilsa5pKFa1FiaLVZVWngk5sQ7IfbMyiaV3HQFPLFQY4\nyMSy9lMtgSakNpLdkVP36+1LbfOYft0P0boMUXoRmdvN3ZJYUQr7jsTuuYG4/EZNM2SQoN3IxDK2\neW3f6ahv7iWYlO/b6ps=</SignatureValue></Signature></ECommerceConnect>'


cert = open('path to cert', 'rb').read()
verified_data = signxml.XMLVerifier().verify(xml_str, x509_cert=cert).signed_xml
`
certificate:
[xs_6859995_cert_txt.txt](https://github.com/XML-Security/signxml/files/6650563/xs_6859995_cert_txt.txt)

**Comment by kislyuk** [comment]
Your peer implementation is non-compliant with the XML Canonicalization standard. It should be specifying an InclusiveNamespaces PrefixList of "ds" and "xenc".

SignXML can verify the signature that you provided if you subclass the XMLVerifier class like so:
```
class MyXMLVerifier(signxml.XMLVerifier):
    def _c14n(self, *args, inclusive_ns_prefixes=None, **kwargs):
        inclusive_ns_prefixes = ["ds", "xenc"]
        return super()._c14n(*args, inclusive_ns_prefixes=inclusive_ns_prefixes, **kwargs)
```
