### ISSUE TITLE
Mypy Support

### ISSUE THREAD

**Issue by weddige** [XML-Security/signxml#174]
Is there any chance, that we will see mypy support? 

I saw you startet at https://github.com/XML-Security/signxml/tree/mypy and it seems, that there isn't too much to do:

```
(.env38) signxml [develop ≡]> mypy .\signxml\ --non-interactive --install-types --ignore-missing-imports
signxml\__init__.py:142: error: Cannot instantiate abstract class "EllipticCurve" with abstract attributes "key_size" and "name"
Found 1 error in 1 file (checked 3 source files)
(.env38) signxml [develop ≡]>
```

Type hints would be awesome, but including mypy in the linting would be a first step in this direction.

**Comment by kislyuk** [comment]
Added in #195
