### ISSUE TITLE
Anyway to remove the namespace prefix?

### ISSUE THREAD

**Issue by rahulbhatt1899** [XML-Security/signxml#178]
I have searched for countless hours to find a way to remove the default namespace 
ds:Signature.

**Comment by kcinnaySte** [comment]
This is something I am also locking for.... But still no Solution. 😞

**Comment by kislyuk** [comment]
Thanks for your interest in SignXML. If you need help, please provide a complete reproduction of the issue you are facing, including complete example code and the difference between what you are expecting and what you see.

I am going to close this issue for now because it does not provide the level of detail necessary to answer the question. Feel free to post more details to get the issue reopened, or open a new issue.

**Comment by rkochar** [comment]
This works for me.

```python
class NoNamespaceXMLSigner(XMLSigner):
    def _get_signature_template(self, *args, **kwargs):
        # Call the original method to get the signature template
        template = super(NoNamespaceXMLSigner, self)._get_signature_template(*args, **kwargs)
        # Recursively remove the 'ds' namespace prefix from all elements and attributes
        self._remove_ds_prefix(template)
        return template

    def _remove_ds_prefix(self, element):
        # Remove 'ds' namespace prefix from the element tag
        if element.tag.startswith("{http://www.w3.org/2000/09/xmldsig#}"):
            element.tag = element.tag.split('}', 1)[1]
        # Update attribute names to remove 'ds' namespace prefix
        for attr_name in list(element.attrib):
            if attr_name.startswith("{http://www.w3.org/2000/09/xmldsig#}"):
                new_attr_name = attr_name.split('}', 1)[1]
                element.attrib[new_attr_name] = element.attrib.pop(attr_name)
        # Apply the same removal for all child elements
        for child in element:
            self._remove_ds_prefix(child)

signer = NoNamespaceXMLSigner(...)
ns = {}
ns[None] = signer.namespaces['ds']
signer.namespaces = ns
```

**Comment by kislyuk** [comment]
@rkochar as far as I know, un-namespaced signatures are not compliant with the schema or the standard. If you have a need to sign with unprefixed/un-namespaced signatures, please open a new issue and provide a specific example of counterparty software that you're trying to interoperate with that requires this.

**Comment by rkochar** [comment]
@kislyuk thanks for your response. I agree with you, however in practice un-namespaced tags are needed. My specific use case (solved with code example above) is the Belastingdienst (Tax office of the Netherlands). As you can imagine, this feature is absolutely critical for a lot of parties (Dutch and international doing business in Netherlands). That said, I do agree this is not ideal.
