### ISSUE TITLE
verify succeeds for enveloped signature and fails for enveloping signature

### ISSUE THREAD

**Issue by georgep7n** [XML-Security/signxml#183]
I get OpenSSL.crypto.Error: [('rsa routines', 'int_rsa_verify', 'bad signature')] when I verify a SAML response signed with an enveloping signature and success when the same SAML response is signed with an enveloped signature.   This is with the current latest release, 2.9.0

**Comment by kislyuk** [comment]
Hello, thank you for your interest in SignXML. If you need help with an issue, please provide a full, self-contained reproduction of the issue that you are seeing, including a description of the expected and observed behavior.
