### ISSUE TITLE
frappe bench 12 was stopped ,

### ISSUE THREAD

**Issue by ailanbelal** [XML-Security/signxml#187]
/usr/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
.
.
.
.
15:37:18 system           | redis_socketio.1 stopped (rc=-15)
15:37:18 system           | redis_cache.1 stopped (rc=-15)
15:37:18 system           | redis_queue.1 stopped (rc=-15)

**Comment by kislyuk** [comment]
This does not appear to be related to SignXML.
