### ISSUE TITLE
How to remove ds: namespace

### ISSUE THREAD

**Issue by SimonCapriles** [XML-Security/signxml#189]
The signed files come with the ds: namespace which seems to be the reason they are rejected by our government validating site [https://validar.firmadigital.bo/](url)
Signed files come out like this
> <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
> </ds:Signature>

And a file signed with different software that is not rejected do not have the "ds:" namespace.
Is there a way to not place the namespace?

**Comment by kislyuk** [comment]
A signature without the XML namespace is not compliant with the XML Digital Signature standard and creating it is outside the scope of SignXML features.

The easiest way to proceed would be to copy the code from SignXML and modify it to do what you want.

Is there a standard that describes the compliance requirements of your validator?

**Comment by SimonCapriles** [comment]
Thank you for making that clear @kislyuk, to tell the truth I am not sure why this site [https://validar.firmadigital.bo/](url) which is where I need my signed xml to pass do not recognize signxml signed xml's because of the "ds" prefix in the namespace.

I am signing now with an express server using this repo [https://gitlab.softwarelibre.gob.bo/adsib/pkcs12-xml](url), if an update comes in which the "ds" prefix could be optional I would rather use this library.

**Comment by kislyuk** [comment]
I see, thanks for clarifying your use case. It sounds like what you're trying to do is configure the namespace prefix map on the signature to make the xml signature namespace the default namespace, not remove it altogether. I added some documentation to the README file with an example of how to do this:
```
signer = signxml.XMLSigner(...)
signer.namespaces = {None: signxml.namespaces.ds}
```
