### ISSUE TITLE
Sign from a .pfx certificate

### ISSUE THREAD

**Issue by danimaribeiro** [XML-Security/signxml#2]
Hi, sorry for the newbie request.
I know that is possible to convert a pfx file to the pem format with PyOpenSSL, but what about override the sign with the possibility to receive a pfx file?

Nice library, a good alternative to pyxmlsec :+1:

**Comment by schlenk** [comment]
Would be nice to have here too. It would also be nice if the sign API could simply take some existing X509/PFX Objects from pyopenssl/cryptograpy instead of requiring PEM serializations.

**Comment by kislyuk** [comment]
PRs welcome :)

**Comment by kislyuk** [comment]
With https://github.com/kislyuk/signxml/commit/bffe24544a4dede9e33282e9b14a187d024dd9f4, you can now pass a PyOpenSSL X509 object directly to the verify method.

The sign method already accepts any cert object that can be an input to PyOpenSSL's `dump_certificate()` (https://github.com/pyca/pyopenssl/blob/master/OpenSSL/crypto.py#L1656). You have to provide the key separately.

**Comment by DanielFerreiraJorge** [comment]
@danimaribeiro were you able to use this lib to sign the nfes? I'm in a point where I sign the xml and SEFAZ return "Rejeição 297 - Assinatura difere do calculado". I'm trying to use this instead o using pysped, because I cannot make pyxmlsec work with python 3... 

thanks

**Comment by danimaribeiro** [comment]
I didn't try yet.
I'm implementing a new lib for it: https://github.com/danimaribeiro/PyTrustNFe
feel free to add your code to it, then we can test with signxml.

**Comment by bittecnologia** [comment]
Heys guys @DanielFerreiraJorge and @danimaribeiro  from Brazil, do you have any example to sing a Nfe XML?  I had the same problem as @DanielFerreiraJorge  had, I'm using Python3 and I just want to sign the Nfe XML, do you have any example?

**Comment by danimaribeiro** [comment]
Sorry, I don't have examples with the signxml yet. I'm still using pyxmlsec.
https://github.com/danimaribeiro/PyTrustNFe/blob/master/pytrustnfe/servicos/Assinatura.py

**Comment by bittecnologia** [comment]
I saw you use xmlsec, do you use Python 2? I'm using Python 3.4 and I can't install it, no way! The problem for me using these libs is that all of them use xmlsec behind the scenes, maybe it's my fault but I already tried a lot of tutorials about that and I couldn't make it works!

**Comment by danimaribeiro** [comment]
Yes, python 2.7, PyXmlSec is not maintaned since a long time ago.
Check this out: https://github.com/mehcode/python-xmlsec

If not working, I think you can provide a test case here, with a xml signed with pyxmlsec in python 2, and the same xml signed with signxml. Probably I won't have enough skills to fix the problem, but we can look at the code to see if we spot the problem.

**Comment by bittecnologia** [comment]
Hey @danimaribeiro  the link you posted I checked this issue https://github.com/mehcode/python-xmlsec/issues/6 and this is exactly what happened to me, and the solution was the version of Cython as Nastya-Kruglikova said. Now the xmlsec was installed, I hope everything will work, thank you
