### ISSUE TITLE
SAML signature produced by signxml 3.0.1 cannot be verified by python3-saml due to c14n transform URI

### ISSUE THREAD

**Issue by simonk52** [XML-Security/signxml#213]
Hi,

(This may not be a bug, but it caught me out, so I'm posting it here in case it helps anyone else)

I use signxml in a SAML identity provider. A couple of services that use my IdP use [python3-saml](https://github.com/onelogin/python3-saml) to parse the SAML responses.

Today I upgraded signxml from 2.10.1 to 3.0.1, and these services started throwing errors suggesting that the signature was invalid. python3-saml [uses xmlsec](https://github.com/onelogin/python3-saml/blob/96ad99e91ed74fcf9dd7175943685eb990dfaefd/src/onelogin/saml2/utils.py#L967) to verify signatures.

I compared a SAML response produced by 2.10.1 with one produced by 3.0.1 and noticed that the c14n transform URI has changed. In 2.10.1, the default `c14n_algorithm` was `http://www.w3.org/2006/12/xml-c14n11`, but in 3.0.1 it has become `http://www.w3.org/2006/12/xmlc14n11#`.

I changed my signing code to explicitly choose `CanonicalizationMethod.CANONICAL_XML_1_1_DEPRECATED_URI` as the `c14n_algorithm`, and python3-saml was able to validate the signatures again.

Since python3-saml uses xmlsec to verify signatures, it's possible that a newer version of xmlsec understands the new URI. I was testing with libxmlsec1-openssl 1.2.31 on Debian Bullseye.

I think the change happened in [this commit](https://github.com/XML-Security/signxml/commit/af3207f9a4ac6f4f40270e201d2f4d2cbc6f914c) that creates an enum for c14n algorithms. I haven't found anything that explains why the new URL is preferred.

Thanks a lot,

Simon

**Comment by kislyuk** [comment]
Thank you for reporting. I have released v3.0.2 which removes the incorrect deprecation (which was caused by incorrect information included in the [RFC 9231 draft](https://www.rfc-editor.org/rfc/rfc9231.html).

**Comment by simonk52** [comment]
Thank you very much!
