### ISSUE TITLE
XMLSignatureProcessor.default_c14n_algorithm was removed

### ISSUE THREAD

**Issue by arthurdejong** [XML-Security/signxml#214]
Hi,

I've noticed that the default_c14n_algorithm property of XMLSignatureProcessor was removed with the 3.0 release but it still seems to be present in what appears to be a test: [test/generate_125_example.py](https://github.com/XML-Security/signxml/blob/develop/test/generate_125_example.py#L34).

This could indicate that this test isn't actually run automatically. I'm not sure if the test should be fixed or removed.

**Comment by kislyuk** [comment]
That is an accessory file to generate a test input. It's not a test in itself. You're right that it needs to be updated to use the 3.0 API, and in general minimized.
