### ISSUE TITLE
Validating reference with implied transformation differs from XML Signature Syntax and Processing Version 1.1 default of C14N

### ISSUE THREAD

**Issue by christru** [XML-Security/signxml#217]
Wanted to create this to bring awareness to a potential issue, apologize I don't have more to contribute at this time.

When validating signatures it appears the implementation defaults to CanonicalizationMethod.Algorithm for references with implied canonicalization (no explicit transform declared.) I believe this will lead to false validation failures for solutions following the standard that set a CanonicalizationMethod.Algorithm that differs from references that leverage the default implied standard. 

XML Signature Syntax and Processing Version 1.1 defines the following:

3.1.1 Reference Generation

...
The Reference Processing Model ([section 4.4.3.2 The Reference Processing Model](https://www.w3.org/TR/xmldsig-core1/#sec-ReferenceProcessingModel)) requires use of Canonical XML 1.0 [[XML-C14N](https://www.w3.org/TR/xmldsig-core1/#bib-XML-C14N)] **as default processing behavior when a transformation is expecting an octet-stream, but the data object resulting from URI dereferencing or from the previous transformation in the list of Transform elements is a node-set. We RECOMMEND that, when generating signatures, signature applications do not rely on this default behavior, but explicitly identify the transformation that is applied to perform this mapping.** In cases in which inclusive canonicalization is desired, we RECOMMEND that Canonical XML 1.1 [[XML-C14N11](https://www.w3.org/TR/xmldsig-core1/#bib-XML-C14N11)] be used.

4.4.3.2 The Reference Processing Model
...
The Transforms specified in this document are defined with respect to the input they require. **The following is the default signature application behavior:**

If the data object is an octet stream and the next transform requires a node-set, the signature application must attempt to parse the octets yielding the required node-set via [[XML10](https://www.w3.org/TR/xmldsig-core/#bib-XML10)] well-formed processing.
**If the data object is a node-set and the next transform requires octets, the signature application must attempt to convert the node-set to an octet stream using Canonical XML [[XML-C14N](https://www.w3.org/TR/xmldsig-core/#bib-XML-C14N)].
Users may specify alternative transforms that override these defaults in transitions between transforms that expect different inputs. The final octet stream contains the data octets being secured. The digest algorithm specified by DigestMethod is then applied to these data octets, resulting in the DigestValue.**
...

I cannot find anything in the standards that states canonicalization method for references should default to CanonicalizationMethod.Algorithm which I interpret being used for signature section only.

Also other frameworks take this approach... more specifically here is some .net documentation on the subject.
excerpt [from .net api docs](https://github.com/dotnet/dotnet-api-docs/blob/08190c45a010dd77732f00b9cb0f59266ae5b495/xml/System.Security.Cryptography.Xml/SignedXml.xml): 
- The `<Transforms>` element  

   Contains an ordered list of `<Transform>` elements that describe how the signer obtained the data object that was digested. A transform algorithm is similar to the canonicalization method, but instead of rewriting the `<Signature>` element, it rewrites the content identified by the `URI` attribute of the `<Reference>` element. The `<Transforms>` element is represented by the <xref:System.Security.Cryptography.Xml.TransformChain> class.  
  
   - Each transform algorithm is defined as taking either XML (an XPath node-set) or bytes as input. If the format of the current data differs from the transform input requirements, conversion rules are applied.  
  
   - Each transform algorithm is defined as producing either XML or bytes as the output.  
  
   - If the output of the last transform algorithm is not defined in bytes (or no transforms were specified), then the [canonicalization method](https://www.w3.org/TR/2001/REC-xml-c14n-20010315) is used as an implicit transform (even if a different algorithm was specified in the `<CanonicalizationMethod>` element).  
  
   - A value of <http://www.w3.org/2000/09/xmldsig#enveloped-signature> for the transform algorithm encodes a rule which is interpreted as remove the `<Signature>` element from the document. Otherwise, a verifier of an enveloped signature will digest the document, including the signature, but the signer would have digested the document before the signature was applied, leading to different answers.

**Comment by kislyuk** [comment]
Your reading looks correct to me. I have made the verifier use `http://www.w3.org/TR/2001/REC-xml-c14n-20010315` as the default when the reference c14n transform is not specified, and added a test case. This will be released shortly.

**Comment by christru** [comment]
Awesome! I had to do decent amount of research when doing interoperability testing,  happy others can benefit from it, thanks for the reply and quick turn around.
