### ISSUE TITLE
Signature verification failed: invalid padding

### ISSUE THREAD

**Issue by Wissperwind** [XML-Security/signxml#220]
```
  File "C:\python310environment\lib\site-packages\signxml\verifier.py", line 398, in verify
    raise InvalidSignature(f"Signature verification failed: {reason}")
signxml.exceptions.InvalidSignature: Signature verification failed: invalid padding
```
Unfortunately there is an error reading my public key. I can't change the key pair because it is already in production.
Is there a possibility to:
- Make signxml print a better error message why a key is not accepted?
- Create an option to specify a padding algorithm that is used by the key?
- Make it more tolerant to different paddings used in x.509 certificates?

**Comment by kislyuk** [comment]
Hi, thanks for your interest in SignXML.

> Make signxml print a better error message why a key is not accepted
What do you believe would be a better error message here? Keep in mind SignXML depends on OpenSSL for actual signature verification, so our ability to introspect the error is limited.

> Create an option to specify a padding algorithm that is used by the key?
Can you outline what such an option would look like? Do you know what padding algorithm your signature used? Is it consistent with the padding, salt length, and MGF specified in your x.509 certificate?

> Make it more tolerant to different paddings used in x.509 certificates?
Can you specify what you mean by "tolerant"? What is the specific algorithm you have in mind?

Currently SignXML uses the [OpenSSL certificate verify API](https://www.pyopenssl.org/en/latest/api/crypto.html#OpenSSL.crypto.verify), which uses the X.509 encoded certificate and its metadata to correctly configure the asymmetric cryptography algorithm used by the public key in the certificate. This API does not have any options for specifying the padding or its associated parameters.

I'm in the middle of migrating SignXML to a more flexible API based on the cryptography library, which does allow specifying the padding, but to complete this migration I need to better understand how X.509 certificates encode padding algorithm metadata in practice (the tools for this encoding are described in e.g. RFC 4055, but I'm not sure how well this applies in practice). I'm not going to introduce a new user-configurable option without being certain that the X.509 certificate itself does not carry the necessary configuration information. With that said, we can definitely discuss what changes need to be made to make SignXML compatible with commonly used padding algorithms, we just need to be precise.
