### ISSUE TITLE
does not generate "Type" attribute in "reference" of "signedproperties" with XAdES signatures

### ISSUE THREAD

**Issue by jcorbalan69** [XML-Security/signxml#224]
does not generate "Type" attribute in "reference" of "signedproperties" with XAdES signatures. 

I have tried in version 3.0 and 3.1, none of them generate the "Type" attribute

<ds:Reference Type="http://uri.etsi.org/01903#SignedProperties"

"Type" is required in the "Reference" element corresponding to the "signedProperties" URI in the XAdES format, as it indicates that the referenced element is a signed property.

**Comment by kislyuk** [comment]
Thank you for reporting this. Fix coming up.

**Comment by kislyuk** [comment]
Fix released in v3.1.1.
