### ISSUE TITLE
SignatureReference inclusive_ns_prefixes not being copied

### ISSUE THREAD

**Issue by mtheisen-solea** [XML-Security/signxml#231]
According to the documentation:
 ```To specify this value separately for reference canonicalizaition, pass a list of one or more [SignatureReference](https://xml-security.github.io/signxml/#signxml.SignatureReference) objects as the reference_uri keyword argument, and set the inclusive_ns_prefixes attribute on those objects.```

This does not seem to be working.

Changing the following line seems to fix this.
https://github.com/XML-Security/signxml/blob/5e0cc150b1bcfef8f2263359f1446680fc7a4ddc/signxml/signer.py#L322
needs to be changed to
```new_references.append(SignatureReference(URI=uri, c14n_method=reference.c14n_method, inclusive_ns_prefixes=reference.inclusive_ns_prefixes))```

**Comment by kislyuk** [comment]
Thank you for finding and reporting this issue, I really appreciate it. Fixed in v3.2.1, please test.
