### ISSUE TITLE
XMLVerifier.verify() backward compatibility issue

### ISSUE THREAD

**Issue by michael0191** [XML-Security/signxml#233]
The xml data lacking a transform entry, "Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments" worked fine in the previous version of signxml (2.9.0) . But it is failed in the 3.2.1. Based on new code,     _default_reference_c14n_method = CanonicalizationMethod.CANONICAL_XML_1_0 is declared in the XMLVerifier class. Previous version of XMLVerifier class doesn't have this default value. Someone can explain why this is changed in newer version?

Best regards,

**Comment by kislyuk** [comment]
Thanks for your interest in SignXML. If you need help, please refer to the instructions in the new issue dialog:

> please provide a single script that yields a complete standalone reproduction of the observed behavior, together with an explanation of the expected behavior and any citations that may be needed to support the expectation.

**Comment by kislyuk** [comment]
I am going to close this issue for now. Please feel free to provide the required details and we can look at them and reopen as needed.
