### ISSUE TITLE
Creating a detached signature

### ISSUE THREAD

**Issue by pglavica** [XML-Security/signxml#236]
Hi,

I would like to create a detached signature.
We have XML that contains element "subject" which should be signed.
In the example.xml I am sending to you in the attachment it is: subject Id="etkdibifdgeafif-habb-bbee-abde-fhafcecaadif

Generated signature should be placed inside element signatureText.
This should be detached signature, from my point of understanding, as shown in following figure:
![image](https://github.com/XML-Security/signxml/assets/100845946/fedc8b3e-955a-4ba4-ad66-43ee8680e0d1)

This is how I generate code:
`el = ET.parse("example.xml")

root = el.getroot()

subject= el.find(".//ns0:subject", {"ns0" : "urn:hl7-org:v3"})
subject_items = subject.items();

subj_ref_uri=""
for item in subject_items:
    if item[0] == "Id":
        subj_ref_uri=item[1]

print(subj_ref_uri)

cert = open("990000023.cer").read()
key = open("990000023.key").read()

signed = XMLSigner(signxml.methods.detached, signature_algorithm="rsa-sha1", c14n_algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315", digest_algorithm="sha1").sign(root, key=key, cert=cert, reference_uri=subj_ref_uri)

signature_text=el.find(".//ns0:signatureText", {"ns0" : "urn:hl7-org:v3"})
signature_text.append(signed)

tree = ET.ElementTree(root)
tree.write("example_signed_python.xml")`

When I try to validate an XML signature on my application on server side (java based), and with my custom java validator it seems to me that reference validity (digest check) is OK, but signature validity is not ok, to be more precise validating the signature value inside signed info.

Can you please help me what am I doing wrong?

[messages.zip](https://github.com/XML-Security/signxml/files/13886710/messages.zip)

**Comment by kislyuk** [comment]
> signature_text=el.find(".//ns0:signatureText", {"ns0" : "urn:hl7-org:v3"})

By attaching the signature, you are altering the signed XML node/document after signing it.

This does not look like a bug within SignXML; I'm going to close this issue for now. Feel free to provide more details if you think this is a bug, and we can reconsider.

**Comment by pglavica** [comment]
Hi,

Are you sure?
Plase check my post.
Signature is detached, and it is placed inside element which is not
included in Signature.
Check the reference URI and what is actually signed.

*********************************************************************************************

Patrik Glavica, *mag.ing.inf.et.comm.techn.*
Team lead & Secuity Master @ Ericsson Nikola Tesla d.d, Zagreb, Croatia
Mobile: +385 91 365 3750

*********************************************************************************************

**Comment by pglavica** [comment]
Please reopen the issue.
Signature is placed inside XML document which is not signed, hence it could not compromise the signature.

Check the reference URI inside the signature and You shall see that subject element it refers to is on different place in document, which is described by the pic I have sent in the original document, detached signature.

**Comment by kislyuk** [comment]
OK, I took another look and while you don't appear to be modifying the signed node when attaching the signature, you _are_ modifying the _signature_.

When you generate a standalone detached signature node, you establish a new XML namespace mapping:
```
<ds:SignedInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"></ds:SignatureMethod><ds:Reference URI="#etkdibifdgeafif-habb-bbee-abde-fhafcecaadif"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"></ds:DigestMethod><ds:DigestValue>umVl7C88qeSfJHQpJ9YG1x99h4o=</ds:DigestValue></ds:Reference></ds:SignedInfo>
```
Notice the `xmlns:ds` tag that establishes the ds namespace prefix mapping. This mapping becomes part of the string signed by the signature.

When you attach the resulting signature node to a parent document, you are allowing the parent document namespace prefix mapping to override the one in the signature. This then changes the canonicalized string to sign and corrupts the signature.

This issue is described in https://github.com/XML-Security/signxml?tab=readme-ov-file#xml-representation-details-configuring-namespace-prefixes-and-whitespace

**Comment by pglavica** [comment]
Hi,

Can you please clarify?
If you check my unsigned message, you can see that there is not http://www.w3.org/2000/09/xmldsig# namespace anywhere in the document.
When I create signature, Signature element out of the box generates the namespace with mentioned prefix. This prefix and namespace is not part of the parent document, and is defined only in the signature.
Can you please point me in the direction where I can get valid signature?

**Comment by pglavica** [comment]
[example_signed_jdk.zip](https://github.com/XML-Security/signxml/files/13900046/example_signed_jdk.zip)
Please check this one.
I used JDK to generate the signature.
Signature element is generated withoud prefix, but is put in xmldsig namespace.
This signature is valid.

**Comment by pglavica** [comment]
Hi,

Yes - now I understand what you were trying to say.
During calculation of signature namespace of the root element was ignored, but during the validation where validator calulates the signature he takes into the consideration namespace when cannonical method is applied.

Now it works:
signer = XMLSigner(signxml.methods.detached,signature_algorithm="rsa-sha1", c14n_algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315", digest_algorithm="sha1")
signer.namespaces = {None: signxml.namespaces.ds, None : "urn:hl7-org:v3"}
signed = signer.sign(root, key=key, cert=cert, reference_uri=subj_ref_uri)
signature_text=el.find(".//ns0:signatureText", {"ns0" : "urn:hl7-org:v3"})
signature_text.append(signed)
