### ISSUE TITLE
Problem with the strip_pem_header function

### ISSUE THREAD

**Issue by hlovdahl** [XML-Security/signxml#241]
We were having some problems with the signature not valid. The problem was located in `signxml/util/__init__.py`. There was an extra new-line character left after stripping away the header and the footer. 
Here is a simple patch that we use:
```
--- __init__.py	2024-01-26 13:40:51.811244782 +0200
+++ my_init.py	2024-01-26 13:40:14.354723717 +0200
@@ -151,9 +151,11 @@

 def strip_pem_header(cert):
     try:
-        return re.search(pem_regexp, ensure_str(cert)).group(1).replace("\r", "")  # type: ignore
+        res = re.search(pem_regexp, ensure_str(cert)).group(1).replace("\r", "")  # type: ignore
     except Exception:
-        return ensure_str(cert).replace("\r", "")
+        res = ensure_str(cert).replace("\r", "")
+    res = res.replace('\n', '')
+    return res


 def add_pem_header(bare_base64_cert):
```
On Ubuntu Linux, python 3.10.

**Comment by kislyuk** [comment]
Thanks for your report. Can you describe your application and the counterparty XML signature software implementation that considers a signature with extra newlines in the certificate node invalid? This behavior is not standards compliant:

> The lexical forms of base64Binary values are limited to the 65 characters of the Base64 Alphabet defined in [[RFC 2045]](https://www.w3.org/TR/xmlschema-2/#RFC2045), i.e., a-z, A-Z, 0-9, the plus sign (+), the forward slash (/) and the equal sign (=), together with the characters defined in [[XML 1.0 (Second Edition)]](https://www.w3.org/TR/xmlschema-2/#XML) as white space. No other characters are allowed.

**Comment by kislyuk** [comment]
Closing due to lack of response.

**Comment by hlovdahl** [comment]
Hello,

The counterparty is a government institution that our software sends reports to.

Python is not widely used for these kind of communications here (certificate fetching and SOAP)  and I was pleased to finally find a library that could be used to create something that actually works.

Previously we have had to resort to Java, but now we are hoping that we finally could rewrite our libraries to use python instead.

I have no doubt about that the newline should be allowed there and that the other party should change their implementation to allow this. I will try to convince them to do this.

In the mean time, maybe you could update your code? It already removes \r `.replace("\r", "")` so also removing \n `.replace("\n", "")` would be highly appreciated.

**Comment by kislyuk** [comment]
Thank you for your response.

`\r` is removed because we are not interested in supporting legacy Windows-style newlines. `\n` is the standard newline in the modern world and we do want to preserve it in PEM-encoded strings unless there is a specific, compelling reason not to.
