### ISSUE TITLE
RSA signature did not verify 

### ISSUE THREAD

**Issue by blitz-cmd** [XML-Security/signxml#253]
Hi,
I am signing xml. So, I am using rsa-sha256 to create signature and digest value of my xml.
I am seeing a weird issue. My xml contains senttimestamp. In timestamp, when the hour is single digit its working fine but  it contains double digit hours, then the rsa signature verify is failing.
What could be the reason for my issue?

**Comment by kislyuk** [comment]
Thanks for your interest in SignXML. If you need help, please follow the instructions in the issue template:

> provide a single script that yields a complete standalone reproduction of the observed behavior, together with an explanation of the expected behavior and any citations that may be needed to support the expectation. Issues that don't provide this information will be closed.

**Comment by kislyuk** [comment]
I am going to close this issue for now as it does not appear to be a SignXML bug. Please feel free to comment if you still need help and we can reopen if clear details are provided.
