### ISSUE TITLE
Namespace issue for <DigestMethod> element in XML signature

### ISSUE THREAD

**Issue by GabrielIFPB** [XML-Security/signxml#264]
Hello, I would like to report a problem I encountered when using the [Library Name] library to update XML documents. The problem is related to the incorrect namespace of the <DigestMethod> element in the signing process.

Problem Description: 
When distributing an XML using the XMLSigner function, the signature generates a <DigestMethod> element with the following namespace:

 <DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha256" / > 
 
 However, when trying to validate the received XML, I get the following error: signxml.exceptions.InvalidInput: 
 
 Expected to find XML element DigestMethod in {http://www.w3.org/2000/09/xmldsig#}Reference 
 
 The library appears to be looking for the <DigestMethod> element in the {http://www.w3.org/2000/09/xmldsig#} namespace, while the generated namespace contains an incorrect suffix {http://www.w3.org/2000/09/xmldsig#sha256}.

**Comment by kislyuk** [comment]
Hi, thanks for your interest in SignXML. If you need help, please provide a complete set of steps to reproduce your issue, including the code you used, the complete document, the observed and expected steps.

Based on the issue description so far, this does not sound like a bug in SignXML. I am going to close this issue for now based on this assessment. Feel free to comment with the details and we can reopen as needed.

**Comment by GabrielIFPB** [comment]
Hello, good afternoon!

I improved the issue that opened, I put an example of the XML and the code
snippets that I am using.

Em seg., 9 de set. de 2024 às 10:43, Andrey Kislyuk <
***@***.***> escreveu:
