### ISSUE TITLE
XMLVerifier still can't decode X509 since 4.0.0

### ISSUE THREAD

**Issue by avtobiff** [XML-Security/signxml#269]
signxml still can't decode X509 since 4.0.0.
Tested with both 4.0.1 and 4.0.2.

Reproduction steps are available in #263.

I would have reopened that issue, but that wasn't possible.

**Comment by kislyuk** [comment]
OK, I released another fix in v4.0.3. Please don't open any new issues, but comment in this one if that does not fix your problem, and I will reopen the issue for you.
