### ISSUE TITLE
Api cosmetics

### ISSUE THREAD

**Issue by pulina** [XML-Security/signxml#28]
Now the signxml object give ability to sign and verify bunch of data pass in constructor argument. Method, algorithm, cert and rest stuff are pass as argument specific method. There Is no option to  sign or verify without creating an object. Why not create simple interface like:

``` python
sign(data, method, algorithm, key, passphrase, cert, c14n_algorithm, reference_uri, digest_algorithm)
```

or use pre-created obj to keep more accurate parameters. In most situation I sign and verify many  different bunch of data with same algorithm and keys. Maybe keep those parameters in fabric object and passing data direct to sign(or veryfi) method. It more intuitive. 

``` python
signer_obj = signxml.xmldsig( algorithm, key, passphrase, cert)
confirmatory_obj = signxml.xmldsig( algorithm, key_pub)
signed_data1 = signer_obj.sign(data1, method)
signed_data2 = signer_obj.sign(data2, method)
signed_data3 = signer_obj.sign(data3, method)
(send_message and get response ...)
if confirmatory_obj.veryfi(response) != get_predicted_signed_part(reponse):
    raise SomeException()
```

**Comment by kislyuk** [comment]
I am very much open to restructuring the API toward this model (where the constructor only takes settings that it makes sense to apply to multiple invocations, while the sign and verify methods are functional/idempotent and take the data input as the first argument).

I'm afraid I don't have the time to do this right now, but contributions on this are very welcome.
