### ISSUE TITLE
Support signing data that has a pre-existing signature somewhere

### ISSUE THREAD

**Issue by soby** [XML-Security/signxml#35]
The signxml._get_signature_regex() function is used to pull signature blocks out of the post-canonicalized data using a regex. When signing a payload that includes another signature, this function removes the internal signatures as well. 

The end result is that the internal, original signatures remain valid but the outer, new signature created by signxml omits the inner signature blocks from the digest and is invalid

**Comment by klondi** [comment]
This should be fixed by pull #46 Can you verify that @soby ?

**Comment by piotrbulinski** [comment]
I was struggling with signing and verifying SAML Responses (with nested pre-signed Assertion), but after updating SignXML to `1.0.0` problem is gone.

**Comment by mbarrien** [comment]
Close?

**Comment by kislyuk** [comment]
Closing. We support signing with other signatures present - please give specific examples if this fails for you.
