### ISSUE TITLE
Signature verification is failing when SAML response has both response and assertion as signed.

### ISSUE THREAD

**Issue by joshiashish** [XML-Security/signxml#40]
While running xmldsig.verify() on a SAML response that has 2 signature sections (one for the response itself and one for the assertion), it throws "Digest Mismatch" exception.

Note that the same verification works with pyxmlsec.

**Comment by joshiashish** [comment]
This is how my SAML response XML looks like:

<?xml version="1.0" encoding="UTF-8"?><saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" Destination="https://saml.starfish.local/saml2/http-post/acs/rxk8bul36Dz25hFIscfx/1" ID="id791678719159012136423084" InResponseTo="_2CAAAAVLpjPItME8wOTAwMDAwMDA0QzkzAAAAxjsqUrobc73SB8s7JeBFDWRjFhkgOS849U-1RXBROUBUZpjHLKXtUzl1n9R2S2gg7o8EzXnq2a8B09xRV7xl4QBxw4ajZLelaYhFgncqsC6IQ3kTGiW0WCP7P3cU7jhu7FTVgYJt_7kKEO5kAPxPVX3j3vZB_ZWeCXcpNNT7g_yPZV48LDHLZLFYT-Yona2gSg4dghKriuk_h0ZauMiALrlKm623HKeoWiEPzxb8iXyu-2JriHsLPc7P7it-g_6r_w" IssueInstant="2016-01-19T10:08:16.147Z" Version="2.0"><saml2:Issuer xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">http://www.okta.com/exk17ynacwf303Fls0h8</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#id791678719159012136423084"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>vJgKVSB9B3slgsnsxAEzqR5LR40=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>UwfXuPZ7ODJuB5BTdHaSDKbu+C5bCpLbXzmEhBYeaXOl5L1gqKM+0W7Y9R5GN4BnLTGmgVH+CKg2ULgs9rw2Ar3VaaFV66Js82eSD/pHwr7jMxa/4RwNO9BPOWQI8I+IttAXl+1wrlCVQQY/Z77z90TDkxR+7y2VIPV76zDZfmlGxR4cobeOjvfOoWLirUK3G7Nvgl9KiAUoh/qiXqIgGWIwCVJoQCn8Alr3i/eveLfLz0FV2XeQdxItTmionwgeQ2WTeO5uvdNvmLCexZS1YW3E5AJ4coV272mX1LlCP77VBz3kQ1wgr5PIMIiDFt9+XOW7w/qQ+129iryronGUpA==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDojCCAoqgAwIBAgIGAUtB0OQuMA0GCSqGSIb3DQEBBQUAMIGRMQswCQYDVQQGEwJVUzETMBEG
A1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEU
MBIGA1UECwwLU1NPUHJvdmlkZXIxEjAQBgNVBAMMCW5ldHNrb3BlOTEcMBoGCSqGSIb3DQEJARYN
aW5mb0Bva3RhLmNvbTAeFw0xNTAxMzEyMTA1MjNaFw00NTAxMzEyMTA2MjNaMIGRMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UE
CgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxEjAQBgNVBAMMCW5ldHNrb3BlOTEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ8K
Rjh+fvImfRzZ9LCoNEkuniI5J61O5CoqWTXrl7M5t/8N1KbF341MY5XjUgIiF5ZCFIAkOVP404K7
IWHB51j9kBDNKki7lzJXoRCNEicZUm4hufnAygJwgpU9aiHSzZe3cxhS++u1niS/X8oRAUCPEWaM
5fYK9wcVHPSnkToYVKT/RUXPCRq3wGO1My5WB/tP/gQChRlDRLZA5C+CZ1SyImhdJvaoNupwYcHf
uxH5F27dDspf3wrn7lLrSdvE6Tl1cB1hNRVVR+KMLdaqnPMtgCyo1kfvsDN2gFF6TnWtJ8cDjo+C
jTcK++QtW4I3/DidGXNmd9E6fjhqKIuSSekCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAZdzWaq/r
MVZG9bOS6tZwIbwlR/ILS5wGBHvd94XAlvM8xRfc8pUGcZw4dS2jtQhXWjARV1n6YC+brNot/91b
TMW74Hwk0mBU1BWrbgCMRby4eiQ0NSc4gjefTDrGDHo+XneTOC5iCTc9ObZLa2fx9RlyGPzn+K3b
QhcxZyHrJgbVmUWQcbPeCnL26HobTDI5OVaTH89NorLyR57d5UWg7ETic45FyTVcVgT1Nbpo1xN9
naCMb1xtZIPOXFU/6iyqVyHI0toF6GgLE6Prvsi/N7MmdvuIJHbhGg1LFCs0RKg9kyRx0Yf7e+d4
4wLrTXTxMpEtz1Mofrf/TmG1g2vzQg==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2p:Status xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol"><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/></saml2p:Status><saml2:Assertion xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="id7916787191640609736159828" IssueInstant="2016-01-19T10:08:16.147Z" Version="2.0"><saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">http://www.okta.com/exk17ynacwf303Fls0h8</saml2:Issuer><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/><ds:Reference URI="#id7916787191640609736159828"><ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/><ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/><ds:DigestValue>2BDGRbPK0hqUFznO12apS1RA/ig=</ds:DigestValue></ds:Reference></ds:SignedInfo><ds:SignatureValue>goYOkw+HSrzcqt3hH0wCzefzbXPYH140eBx5EhXloOeJhA3lohfaRIxLcCwWqyhaCmPOx5WB2jOs8nNQQZUdSLU23zBp7M0AAp+DgSEx5adr/LwR7FfzQIfaF62isXU+koY1Nw9BZ0R13kCMUIXuQDjlUsBD/8RW8l9zctILM0GhkpEirzwfdrb6l29UmbDjgEgpTlqzHCvquWl2buBmDaWkFbMOqmvV6AqhXuI7UarK7iBYg/wiHKmtJMSYFl5oIvHkCFZniyPdehmQ4Uakc0PrvfLfmd8KBDK5oG3VCU3unor7Hm4XnDRTm+vxzUDEuGB5ezEbQ2g6oW6jCsk6vA==</ds:SignatureValue><ds:KeyInfo><ds:X509Data><ds:X509Certificate>MIIDojCCAoqgAwIBAgIGAUtB0OQuMA0GCSqGSIb3DQEBBQUAMIGRMQswCQYDVQQGEwJVUzETMBEG
A1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UECgwET2t0YTEU
MBIGA1UECwwLU1NPUHJvdmlkZXIxEjAQBgNVBAMMCW5ldHNrb3BlOTEcMBoGCSqGSIb3DQEJARYN
aW5mb0Bva3RhLmNvbTAeFw0xNTAxMzEyMTA1MjNaFw00NTAxMzEyMTA2MjNaMIGRMQswCQYDVQQG
EwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQGA1UEBwwNU2FuIEZyYW5jaXNjbzENMAsGA1UE
CgwET2t0YTEUMBIGA1UECwwLU1NPUHJvdmlkZXIxEjAQBgNVBAMMCW5ldHNrb3BlOTEcMBoGCSqG
SIb3DQEJARYNaW5mb0Bva3RhLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAJ8K
Rjh+fvImfRzZ9LCoNEkuniI5J61O5CoqWTXrl7M5t/8N1KbF341MY5XjUgIiF5ZCFIAkOVP404K7
IWHB51j9kBDNKki7lzJXoRCNEicZUm4hufnAygJwgpU9aiHSzZe3cxhS++u1niS/X8oRAUCPEWaM
5fYK9wcVHPSnkToYVKT/RUXPCRq3wGO1My5WB/tP/gQChRlDRLZA5C+CZ1SyImhdJvaoNupwYcHf
uxH5F27dDspf3wrn7lLrSdvE6Tl1cB1hNRVVR+KMLdaqnPMtgCyo1kfvsDN2gFF6TnWtJ8cDjo+C
jTcK++QtW4I3/DidGXNmd9E6fjhqKIuSSekCAwEAATANBgkqhkiG9w0BAQUFAAOCAQEAZdzWaq/r
MVZG9bOS6tZwIbwlR/ILS5wGBHvd94XAlvM8xRfc8pUGcZw4dS2jtQhXWjARV1n6YC+brNot/91b
TMW74Hwk0mBU1BWrbgCMRby4eiQ0NSc4gjefTDrGDHo+XneTOC5iCTc9ObZLa2fx9RlyGPzn+K3b
QhcxZyHrJgbVmUWQcbPeCnL26HobTDI5OVaTH89NorLyR57d5UWg7ETic45FyTVcVgT1Nbpo1xN9
naCMb1xtZIPOXFU/6iyqVyHI0toF6GgLE6Prvsi/N7MmdvuIJHbhGg1LFCs0RKg9kyRx0Yf7e+d4
4wLrTXTxMpEtz1Mofrf/TmG1g2vzQg==</ds:X509Certificate></ds:X509Data></ds:KeyInfo></ds:Signature><saml2:Subject xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">ashish1@netskope.com</saml2:NameID><saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData InResponseTo="_2CAAAAVLpjPItME8wOTAwMDAwMDA0QzkzAAAAxjsqUrobc73SB8s7JeBFDWRjFhkgOS849U-1RXBROUBUZpjHLKXtUzl1n9R2S2gg7o8EzXnq2a8B09xRV7xl4QBxw4ajZLelaYhFgncqsC6IQ3kTGiW0WCP7P3cU7jhu7FTVgYJt_7kKEO5kAPxPVX3j3vZB_ZWeCXcpNNT7g_yPZV48LDHLZLFYT-Yona2gSg4dghKriuk_h0ZauMiALrlKm623HKeoWiEPzxb8iXyu-2JriHsLPc7P7it-g_6r_w" NotOnOrAfter="2016-01-19T10:13:16.147Z" Recipient="https://saml.starfish.local/saml2/http-post/acs/rxk8bul36Dz25hFIscfx/1"/></saml2:SubjectConfirmation></saml2:Subject><saml2:Conditions NotBefore="2016-01-19T10:03:16.147Z" NotOnOrAfter="2016-01-19T10:13:16.147Z" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:AudienceRestriction><saml2:Audience>https://linkhhh.my.salesforce.com</saml2:Audience></saml2:AudienceRestriction></saml2:Conditions><saml2:AuthnStatement AuthnInstant="2016-01-19T10:08:16.147Z" SessionIndex="_2CAAAAVLpjPItME8wOTAwMDAwMDA0QzkzAAAAxjsqUrobc73SB8s7JeBFDWRjFhkgOS849U-1RXBROUBUZpjHLKXtUzl1n9R2S2gg7o8EzXnq2a8B09xRV7xl4QBxw4ajZLelaYhFgncqsC6IQ3kTGiW0WCP7P3cU7jhu7FTVgYJt_7kKEO5kAPxPVX3j3vZB_ZWeCXcpNNT7g_yPZV48LDHLZLFYT-Yona2gSg4dghKriuk_h0ZauMiALrlKm623HKeoWiEPzxb8iXyu-2JriHsLPc7P7it-g_6r_w" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion"><saml2:AuthnContext><saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml2:AuthnContextClassRef></saml2:AuthnContext></saml2:AuthnStatement></saml2:Assertion></saml2p:Response>

**Comment by kislyuk** [comment]
Thanks for reporting. I haven't had the chance to look at this yet, but I will be shortly.

**Comment by joshiashish** [comment]
Hi @kislyuk ,

Did you get a chance to look into it.

Thanks,
Ashish

**Comment by klondi** [comment]
@joshiashish this should be fixed now, can you verify that?

**Comment by anishchadayappan** [comment]
Checked, working as expected

**Comment by kislyuk** [comment]
Closing since the underlying issue appears to have been resolved. Please re-open if you still see this happening!
