### ISSUE TITLE
signxml.InvalidCertificate: [20, 0, 'unable to get local issuer certificate']

### ISSUE THREAD

**Issue by sigurjonmag** [XML-Security/signxml#61]
I'm tying to add xml signature to a XML file 
but don't seem  to validate the it. 
What am I doing wrong ? 
Am I parsing the xml file incorrectly ?

Here is the python code:
####### 
from signxml import xmldsig
import xml.etree.ElementTree as ET
cert = open("x.pem").read()
key = open("x.key").read()
tree = ET.parse('alert2.xml')
root = tree.getroot()
signed_root = xmldsig(root).sign(key=key, cert=cert)
verified_data = xmldsig(signed_root).verify()
###

The xml file is attached just remove the .txt at the end 
[alert2.xml.txt](https://github.com/XML-Security/signxml/files/435181/alert2.xml.txt)

**Comment by kislyuk** [comment]
How did you generate your certificate?

**Comment by sigurjonmag** [comment]
They are bought from Comodo

**Comment by kislyuk** [comment]
It's expected that you will either pass the full certificate chain when signing (including any necessary intermediate certificates), or pass the specific signing certificate when verifying (using the `x509_cert` keyword argument).

**Comment by sigurjonmag** [comment]
I pretty sure i have the full root certificate. 
Any suggestions?

**Comment by kislyuk** [comment]
You are not passing the root certificate and intermediates to `verify()`. You must do so.
