### ISSUE TITLE
Generate signature for Invoice XML

### ISSUE THREAD

**Issue by ovnicraft** [XML-Security/signxml#67]
I am testing this library to replace xades lib in JAVA, now in java app (called in subprocess from python), i got this signature element https://gist.github.com/ovnicraft/09865acf32a6fbb54b4b098205ed054d

Trying to do the same with this lib, has issues around issues, Integers IDS `<ds:KeyInfo Id="Certificate188326">` and i want to know signature method is compute over data to sign ? in any special format ? or just bytes  ?

**Comment by kislyuk** [comment]
Sorry about the initial lack of response on this issue. I was unable to understand your question, so I couldn't help you. If you can re-state your question, I may be able to help.

**Comment by ovnicraft** [comment]
Hi, i am looking for replace my java program to sign XML documents (invoices), so my gist is the example of the element what i need to include in my XML.
I need to implement Xades standar http://uri.etsi.org/01903/v1.3.2/ts_101903v010302p.pdf
All electronic invoices has XML representation with enveloped signature.

I am looking for help to do this, i am new with this standard.

**Comment by ovnicraft** [comment]
@kislyuk if you can give some guide to implement Xades-BES with this lib would appreciated.

**Comment by kislyuk** [comment]
@ovnicraft, unfortunately this library does not support XAdES. Supporting that standard would be a large task that I currently don't have the time for. PRs are welcome.
