### ISSUE TITLE
etree.tostring() returns blank string

### ISSUE THREAD

**Issue by natebessa** [XML-Security/signxml#71]
I'd like to use signxml to validate the signature in a POST'ed SAML response from an IdP redirect to our app (the SP). The IdP's x509 cert is contained in a metadata file on our server. I seem to be getting a problem however in this line from signxml/__init__.py (line 692, in verify).

`signature = fromstring(etree.tostring(signature_ref), parser=parser)`

The error is:
> XMLSyntaxError: None 

This is occurring because etree.tostring(signature_ref) returns an empty string ''. I haven't been able to figure out why. 

In the console, if I call signature_ref, this is what it looks like:
><Element {http://www.w3.org/2000/09/xmldsig#}Signature at 0x7f66810d81b8>

The initial verify() call we are using looks like this:

`assertion_data = XMLVerifier().verify(decoded_saml, x509_cert=x509_cert_from_metadata).signed_xml`

And decoded_saml is a string with the following:

```
<samlp:Response xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" Consent="urn:oasis:names:tc:SAML:2.0:consent:unspecified" Destination="https://[sp acs page]" ID="ba9878756106f75a738d41f850347714" IssueInstant="2016-10-31T22:12:40Z" Version="2.0">
           <saml:Issuer>https://[idp page]saml:Issuer>
           <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
              <ds:SignedInfo>
                 <ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                 <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" />
                 <ds:Reference URI="#ba9878756106f75a738d41f850347714">
                    <ds:Transforms>
                       <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
                       <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
                    </ds:Transforms>
                    <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" />
                    <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>
                 </ds:Reference>
              </ds:SignedInfo>
              <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj
        rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+
        QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH
        Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q
        eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ==</ds:SignatureValue>
           </ds:Signature>
           <samlp:Status>
              <samlp:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
           </samlp:Status>
           <saml:Assertion ID="fa5bb74c5a052b7ff36668c874e006be" IssueInstant="2016-10-31T22:12:40Z" Version="2.0">
              <saml:Issuer>https://[idp page]</saml:Issuer>
              <saml:Subject>
                 <saml:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified" NameQualifier="[idp page]">[login username]</saml:NameID>
                 <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
                    <saml:SubjectConfirmationData NotOnOrAfter="2016-11-01T10:12:40Z" Recipient="[sp acs page]" />
                 </saml:SubjectConfirmation>
              </saml:Subject>
              <saml:Conditions NotBefore="2016-10-31T22:11:40Z" NotOnOrAfter="2016-11-01T10:12:40Z">
                 <saml:AudienceRestriction>
                    <saml:Audience>https://[sp_url]</saml:Audience>
                 </saml:AudienceRestriction>
              </saml:Conditions>
              <saml:AuthnStatement AuthnInstant="2016-10-31T22:12:32Z" SessionIndex="fa5bb74c5a052b7ff36668c874e006be">
                 <saml:SubjectLocality Address="10.251.71.100" DNSName="0:0:0:0:0:0:0:1" />
                 <saml:AuthnContext>
                    <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml:AuthnContextClassRef>
                 </saml:AuthnContext>
              </saml:AuthnStatement>
           </saml:Assertion>
        </samlp:Response>
```

Do you have any idea why the tostring() is returning a blank string, causing verify to be unable to create an etree out of the signature section of the XML?

Thanks so much. This is a really useful library so I'm hoping I can get it to work!

**Comment by kislyuk** [comment]
I'm as surprised as you are that tostring can fail like that. My best guess
so far is that this is due to an uncaught libxml2 error in LXML, including
possibly an OOM. ```etree.tostring(etree.fromstring(b'<ds:Signature
xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\n
 <ds:SignedInfo>\n                 <ds:CanonicalizationMethod Algorithm="
http://www.w3.org/2001/10/xml-exc-c14n#"/>\n
<ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>\n
                <ds:Reference URI="#ba9878756106f75a738d41f850347714">\n
                 <ds:Transforms>\n                       <ds:Transform
Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n
                <ds:Transform Algorithm="
http://www.w3.org/2001/10/xml-exc-c14n#"/>\n
 </ds:Transforms>\n                    <ds:DigestMethod Algorithm="
http://www.w3.org/2000/09/xmldsig#sha1"/>\n
 <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>\n
      </ds:Reference>\n              </ds:SignedInfo>\n
 <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj\n

 rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+\n

 QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH\n

 Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q\n
       eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ==</ds:SignatureValue>\n
    </ds:Signature>'))``` works for me. Does it work for you? If so, my
suggestion is to try to reduce this to a test case that fails by
eliminating moving parts from your app.

**Comment by natebessa** [comment]
Thanks for the quick reply kislyuk. Strangely, that does not work for me, as it also returns ''. 

`etree_string = etree.tostring(etree.fromstring(b'<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\n <ds:SignedInfo>\n <ds:CanonicalizationMethod Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>\n <ds:Reference URI="#ba9878756106f75a738d41f850347714">\n <ds:Transforms>\n <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n <ds:Transform Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n </ds:Transforms>\n <ds:DigestMethod Algorithm=" http://www.w3.org/2000/09/xmldsig#sha1"/>\n <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>\n </ds:Reference>\n </ds:SignedInfo>\n <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj\n rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+\n QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH\n Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q\n eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ==</ds:SignatureValue>\n </ds:Signature>'))`

Returns
> ''

Did it/was it supposed to return the following?

`b'<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\n <ds:SignedInfo>\n <ds:CanonicalizationMethod Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>\n <ds:Reference URI="#ba9878756106f75a738d41f850347714">\n <ds:Transforms>\n <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n <ds:Transform Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n </ds:Transforms>\n <ds:DigestMethod Algorithm=" http://www.w3.org/2000/09/xmldsig#sha1"/>\n <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>\n </ds:Reference>\n </ds:SignedInfo>\n <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj\n rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+\n QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH\n Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q\n eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ==</ds:SignatureValue>\n </ds:Signature>`

**Comment by kislyuk** [comment]
Yes! Excellent, we have a reduced repro then. What is your python and LXML
version and platform?

**Comment by kislyuk** [comment]
Also, just to verify, can you reproduce this without loading anything else
in python? e.g. `python -c'from lxml import etree;
print(etree.tostring(etree.fromstring(b'...')))`

**Comment by natebessa** [comment]
Here my my versions:
> certifi==2016
> .9.26
> cffi==1.8.3
> click==6.6
> cryptography==1.4
> defusedxml==0.4.1
> eight==0.3.3
> enum34==1.1.6
> Flask==0.11.1
> future==0.15.2
> idna==2.1
> importlib==1.0.4
> ipaddress==1.0.17
> itsdangerous==0.24
> Jinja2==2.8
> lxml==3.6.4
> MarkupSafe==0.23
> ndg-httpsclient==0.4.2
> pyasn1==0.1.9
> pycparser==2.17
> pyOpenSSL==16.2.0
> signxml==2.2.1
> six==1.10.0
> Werkzeug==0.11.11

In a python shell in the virtualenv of the terminal I ran this:

> from lxml import etree 
> print(etree.tostring(etree.fromstring(b'...')))

But got this error:

> File "<stdin>", line 1, in <module>
>   File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:77737)
>   File "src/lxml/parser.pxi", line 1830, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:116674)
>   File "src/lxml/parser.pxi", line 1718, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:115324)
>   File "src/lxml/parser.pxi", line 1090, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:109723)
>   File "src/lxml/parser.pxi", line 584, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:103584)
>   File "src/lxml/parser.pxi", line 694, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:105238)
>   File "src/lxml/parser.pxi", line 624, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:104147)
> lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by kislyuk** [comment]
Yeah I meant you should replace ... with the b'<ds:Signature...' string
from before.

**Comment by natebessa** [comment]
Whoops, just realized that too...

print(etree.tostring(etree.fromstrin`g(b'<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">\n <ds:SignedInfo>\n <ds:CanonicalizationMethod Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>\n <ds:Reference URI="#ba9878756106f75a738d41f850347714">\n <ds:Transforms>\n <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>\n <ds:Transform Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>\n </ds:Transforms>\n <ds:DigestMethod Algorithm=" http://www.w3.org/2000/09/xmldsig#sha1"/>\n <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>\n </ds:Reference>\n </ds:SignedInfo>\n <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj\n rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+\n QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH\n Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q\n eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ=`=</ds:SignatureValue>\n </ds:Signature>')))

Does successfully return 

```
<ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
 <ds:SignedInfo>
 <ds:CanonicalizationMethod Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>
 <ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
 <ds:Reference URI="#ba9878756106f75a738d41f850347714">
 <ds:Transforms>
 <ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
 <ds:Transform Algorithm=" http://www.w3.org/2001/10/xml-exc-c14n#"/>
 </ds:Transforms>
 <ds:DigestMethod Algorithm=" http://www.w3.org/2000/09/xmldsig#sha1"/>
 <ds:DigestValue>q3oMeZfO8NKXmQMSMhz3NKDza7Y=</ds:DigestValue>
 </ds:Reference>
 </ds:SignedInfo>
 <ds:SignatureValue>rH2r/dc2lE8V07aZGnr1PwZjtSeKpGDMsaUbNSE0/NEOeCQIzZ8701b7SV1NzvhCLmRde4r35YJj
 rBPPkV34mNrlCWjXgIRrnucHag0d9pOxD5xm8gaElD1Qglwj3TA3kArn6iJJHtON0gCzTxJ5ooT+
 QkwUm8zkxCtSGUmUR3CuNgwPncK9EijOyIk5aJToX5lgyz1GjNzZnsothuWreDIw24EYDNAyBePH
 Vgfwj2oEw056obSnVJVtdmZyWlhfeYFUL4xExAJqrvIJ7gyczg1yY1OKBFQ/BUxsxpSziY4Zz01q
 eiaXgB/P4v7+0qXW/ktiMK+wwv2ApcHNoEccrQ==</ds:SignatureValue>
 </ds:Signature>
```

**Comment by natebessa** [comment]
Also my python version is 2.7.6

**Comment by kislyuk** [comment]
OK. So the fact that lxml functions fine standalone means either you're
loading a library in your app that is doing something weird to interfere
with it, or your app runs out of memory in the course of running but
silently fails like this instead of crashing, or your app otherwise
configures the python interpreter in a way that causes it to fail (perhaps
even turning off assertions with python -O might cause this).

Are you running your app in a wsgi runtime or some other app runtime?

The best bet is to insert this test case that we came up with, followed by
quit(), as early as possible in the app loading process to see when it
starts to fail. If it doesn't fail, try to bisect the code path with the
test case until it starts to fail.

What is your python version and platform?

**Comment by natebessa** [comment]
Great tips, thank you! I'm indeed running the app with wsgi. The platform is Flask and the python version is 2.7.6. Let me see what I can strip away. I'll post my results here later today.

**Comment by natebessa** [comment]
I wonder if this is an issue with Flask. I've pretty much stripped out all other libraries and imports besides lxml from the app and keep getting a blank string from our test case. 

But in a python interpreter, if I import all the pip libraries, the test case is alway sfine.

**Comment by kislyuk** [comment]
Have you managed to make the test case fail in a standalone Python script
(not running under mod_wsgi)? At this point the wsgi harness would be my
prime suspect.

**Comment by natebessa** [comment]
Do you mean running Flask from my machine and testing it that way? I will give that a shot tonight.

By the way I found that in this thread -- https://bugs.launchpad.net/lxml/+bug/1556625 -- someone checked their lxml compilation versions. I too have the same problem when I check mine:

>>> from lxml import etree
>>> print("%-20s: %s" % ('lxml.etree', etree.LXML_VERSION))
lxml.etree          : (3, 6, 4, 0)
>>> print("%-20s: %s" % ('libxml compiled', etree.LIBXML_COMPILED_VERSION))
libxml compiled     : (2, 9, 4)

**Comment by natebessa** [comment]
I did some local testing and am seeing that this definitely has to do with the WSGI application.

**Comment by kislyuk** [comment]
By wsgi you mean mod_wsgi under apache, right? I haven't looked into this much, but this seems like a good place to start: http://modwsgi.readthedocs.io/en/develop/user-guides/application-issues.html

**Comment by natebessa** [comment]
Thanks. I ended up setting up a newer and cleaner server environment, and lxml worked there, as did your signxml library. Signature verification passed too :) Thanks for all your help!!

Perhaps a topic for a separate thread, but do you have any recommendations for how to test that the verification will catch bad signatures? Simply entering random characters into the SignatureValue section won't work as your library (nicely) points out length or byte type issues. Would love to see a test case simply return 'bad signature'.

**Comment by kislyuk** [comment]
Sorry about the late response to this. To test for a bad signature, the trick I usually use is to generate a good signature, then change just one byte in it (for example, by changing the case of a letter in the middle of the base64 encoded signature, or something like that).
