### ISSUE TITLE
update to cryptography 1.6, lxml 3.6?

### ISSUE THREAD

**Issue by rhoerbe** [XML-Security/signxml#74]
An upgrade would have among others following benefits:
- cryptography 1.6 includes support for sierra and wheels include openssl 1.0.2i.
- use of system-site packages from python3.5 via macports (which are on 1.6)
- macports inclused also lxml==3.6.0 for py35

**Comment by kislyuk** [comment]
The cryptography dependency range constraint should be fixed in https://github.com/XML-Security/signxml/commit/6482670 which I just released. lxml was already at 3.6.0.

**Comment by mbarrien** [comment]
This should be closed now by #84 and #85.
