### ISSUE TITLE
XAdES support

### ISSUE THREAD

**Issue by kislyuk** [XML-Security/signxml#90]
* https://www.w3.org/TR/XAdES/

* https://en.wikipedia.org/wiki/XAdES

**Comment by gdalvarezr** [comment]
This feature will be nice. Thanks for good work

**Comment by ovnicraft** [comment]
Its possible implement it. ?

**Comment by kislyuk** [comment]
This is unlikely to happen soon unless the work is sponsored.

**Comment by ovnicraft** [comment]
We are open to fund it, we are working with java and need to migrate to python, can we chat about it ? i am on telegram

**Comment by blaggacao** [comment]
I'll join. I'm a old acquaintance of @ovnicraft and we might share the same needs...
If I start, should I start as a PR or a `signxml-xades`?

**Comment by kislyuk** [comment]
Sorry, I totally missed the previous comment.

I would love to review a PR for this functionality.

**Comment by blaggacao** [comment]
That's a go, then :smile:

**Comment by kislyuk** [comment]
XAdES support has been added and released in the v3 series.
