### ISSUE TITLE
Excract signature key into an external element

### ISSUE THREAD

**Issue by nagylzs** [XML-Security/signxml#94]
I need to create a signature of an XML that involves the certificate that is used to sign the XML. In order to do this, the certificate that is used to create the signature cannot be embedded inside the KeyInfo element.

In other words: instead of having Signature/KeyInfo/X509Data/X509Certificate, I need to extract the certificate into a separate wsse Security/BinarySecurityToken. After the BinarySecurityToken has been created, I need to create the signature for that BinarySecurityToken element (and other elements as well), and that Signature element should have a wsse:SecurityTokenReference instead of an X509Data element.

This is a requirement by the web serice that I'm trying to use. And even though it is perfectly valid to embed the certificate into an X509Data, but it is impossible to embed the signed data into the signature itself, so they must be separated.

Problem: then XMLSigner.sign() does not allow me to specify an external wsse:SecurityTokenReference (instead of embedding the X509Data). I can probably hack the signer and manually replace the X509Data element with a SecurityTokenReference element but that is very ugly.

Do you think that this scenario is common enough, and it is worth changing the parameter list of the XMLSigner.sign method? Or should I just use the hacked version?

**Comment by kislyuk** [comment]
Hi @nagylzs, sorry about the delay in my response here. You're talking about specifically what it would take to support WS-Security, right? I've looked at supporting WS-Security previously, but abandoned the work to support it before I completed everything. I unfortunately don't have the time to look into the missing parts right now, but I'm open to pull requests implementing WS-Security signing support. I'm not certain precisely what that would involve - it's worth thinking about the most user-friendly API - but perhaps it's by passing a wsse:SecurityTokenReference like you said.

**Comment by nagylzs** [comment]
Same is the case with me. I had to do this, but I have constructed the xml in a way that is specific to my application. But I'm willing to send in more general code for ws security later, when I'll have more time. Until then, anyone who needs code samples please contact me. I know it is hard to find even examples for python + ws security + xml signing on the net.

**Comment by kislyuk** [comment]
Closing this due to lack of further response.
