### ISSUE TITLE
No support for InclusiveNamespaces for signing?

### ISSUE THREAD

**Issue by nagylzs** [XML-Security/signxml#95]
I see that the verify() method looks for transform elements and honours the ec:InclusiveNamespaces / prefixlist attributes. But the sign() method has no support for this, right? Here at line 350:

https://github.com/XML-Security/signxml/blob/master/signxml/__init__.py#L350

The self._c14n is called without the inclusive_ns_prefixes parameter. Could we add an `inclusive_ns_prefixes `parameter to the sign() method?

**Comment by nagylzs** [comment]
We would also have to generate ds:Transform and ds:CanonicalizationMethod elements.

**Comment by kislyuk** [comment]
Hi @nagylzs, this is correct. Can you give me an idea of why you need this functionality? The sign() method is intended to provide sane defaults, which application are you working with that requires the use of InclusiveNamespaces PrefixList?

**Comment by nagylzs** [comment]
I'm working on a healthcare system that sends data to the government's server. The server is written in oracle java ee, and ot seems that the xml signature is accepted only with a specific prefixlist. I don't know why, and I can't change it. I have to conform. BTW i have already implemented this on a lower level (lxml+cryptography) because I had to do it before a deadline.

**Comment by kevliu** [comment]
I have the same issue here. I need this to generate a valid SAML assertion for a Salesforce integration.

**Comment by nagylzs** [comment]
kevliu, if the other party is using oracle java EE for verifying the signature, then I might be able to send you some code that will help. But the code is very messy, really.

**Comment by kevliu** [comment]
Thanks @nagylzs  -- I think the other party just wants an ec:InclusiveNamespaces element as such: 
`<ds:Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11">
	<ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2006/12/xml-c14n11" PrefixList="xs"/>
</ds:Transform>`

I will try using lxml to insert that into the signed document.

**Comment by nagylzs** [comment]
That is not going to work. That element only specifies how the canonicalization should be done before the content is signed. The actual canonicalization used will not be affected by adding an extra element. In other words: you will be lying about the c14n method, and it will result in a different signature. The signature check will fail and your assertion will fail.

**Comment by kevliu** [comment]
Thanks @nagylzs , you are correct. Do you have that "messy code" handy?

**Comment by nagylzs** [comment]
Sorry for the late answer, I'm sending it in an email

**Comment by ragerin** [comment]
What is the state of this issue?
I am encountering the same need, but haven't had any luck.

**Comment by kislyuk** [comment]
PRs are welcome. I am not currently actively developing this feature. I may be able to develop it if there is strong desire for it and sponsorship involved.

**Comment by kislyuk** [comment]
This is now supported via `signxml.XMLSigner.sign(payload_inclusive_ns_prefixes=..., signature_inclusive_ns_prefixes=...)`.
