### ISSUE TITLE
self signed certificate issue

### ISSUE THREAD

**Issue by shank233** [XML-Security/signxml#96]
Hi,

I'm trying to verify a XML signature in SAML response but it's giving me following error:
signxml.exceptions.InvalidCertificate: [18, 0, 'self signed certificate']

Does signxml not support self signed certificate?

Thanks,
Shashank

**Comment by kislyuk** [comment]
You should be able to use your self-signed certificate, as long as you add it to your platform trust store (certificate authority list).

You can't bypass the certificate verification process, unless you want to fork or monkey-patch the library. That be too dangerous and prone to bugs. You're welcome to edit or monkey patch the code in your test environment, to bypass the validation stage, just don't do it in production as that would defeat the purpose of this library.
