### ISSUE TITLE
changing namespace in source xml problem

### ISSUE THREAD

**Issue by lwp007** [XML-Security/signxml#97]
hello, i found that when sign or verify the xml with signxml, it will automaticly change the original namespace with namespaces like ns0, ns1, etc...
is there a way to keep the orignal namespace in raw xml, thanks a lot!

**Comment by kislyuk** [comment]
Could you please provide a working example test case, with your input, the produced output, and your expected output?

**Comment by lwp007** [comment]
for example, i have a raw xml file (C:\raw.xml) like this:

<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://test.com/abc" AttributeConsumingServiceIndex="0" ID="testid" IssueInstant="TEST" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">TEST</saml:Issuer><samlp:NameIDPolicy AllowCreate="False" /></samlp:AuthnRequest>

and after these codes below:

keycontent = open( 'keys/private-key.pem', 'rt').read()
certcontent = open( 'keys/certificate.pem', 'rt').read()
f = open("C:/raw.xml","r")
lines = f.readlines()
root = ElementTree.fromstring(lines.pop())
signed_root = XMLSigner(method = signxml.methods.enveloped, signature_algorithm=u'rsa-sha1', digest_algorithm=u'sha1', c14n_algorithm=u'http://www.w3.org/2001/10/xml-exc-c14n#').sign(root, key=keycontent, passphrase='123456', cert=certcontent)
print ElementTree.tostring(signed_root)

i get the output below:

<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://test.com/abc" AttributeConsumingServiceIndex="0" ID="testid" IssueInstant="TEST" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer>TEST</ns1:Issuer><ns0:NameIDPolicy AllowCreate="False" /><ns2:Signature><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><ns2:Reference URI="#testid"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><ns2:DigestValue>x04GTDuVHS4Je+cdGGVHybck3iI=</ns2:DigestValue></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue>aJUtq+p9ZRNGn0UtLzeqE6Lu66B4akSx68wTTKLHYBb5vMen/Q4BwFNh3OscNoJW7BQbOgNTyBUaJm0B/hnpIph5/TG7GHtsINOS4Bg8Xr6HpyGY9s5OWqlEnMPod/9NTklXjPxVuHrBfUmTsdK9DkJJkwzHTtCth8+qDL0Gzxrk3gpElLcSfKbivjPuhwK/RwNLcc2czbYY1TO6dxBNt8RrYUCwqpnfRnDcVLNcWHeno5Tdo5Vsw8oqMoCW3tlw8jVUJdjTuWbX9rG9bb+yYfjKGR71n1ge8wUnYDnmexV2Intclek0kPKUMHM7ZbIqNzemsTbEFPpXmW2q57gldg==</ns2:SignatureValue><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>MIIDzTCCArWgAwIBAgIEHn6upzANBgkqhkiG9w0BAQsFADCBljELMAkGA1UEBhMC
Q04xEjAQBgNVBAgTCUd1YW5nZG9uZzEsMCoGA1UEBxMjQmFudGlhbiwgTG9uZ2dh
bmcgRGlzdHJpY3QsU2hlbnpoZW4xJjAkBgNVBAoTHUh1YXdlaSBUZWNobm9sb2dp
ZXMgQ28uLCBMdGQuMQ4wDAYDVQQLDAVCUCZJVDENMAsGA1UEAxMEY3NjZzAeFw0x
NzA4MjgxMjIxMjlaFw00NTAxMTIxMjIxMjlaMIGWMQswCQYDVQQGEwJDTjESMBAG
A1UECBMJR3Vhbmdkb25nMSwwKgYDVQQHEyNCYW50aWFuLCBMb25nZ2FuZyBEaXN0
cmljdCxTaGVuemhlbjEmMCQGA1UEChMdSHVhd2VpIFRlY2hub2xvZ2llcyBDby4s
IEx0ZC4xDjAMBgNVBAsMBUJQJklUMQ0wCwYDVQQDEwRjc2NnMIIBIjANBgkqhkiG
9w0BAQEFAAOCAQ8AMIIBCgKCAQEAg9hHlpiyDN3wWp8sWfeSQI8rA8CxnMtr6dRX
Y2yTiBSbsVq9ygJPNtDXKHZqN2funG/dDN46n2fkrK/pA3pDeIwDefxkwfUCRQPl
kPJ4/gbKsbeHpY9JxQ0ZgfGs+AMuEK6BMH0LWKoWOxiWu/D/lepnQS/mQJKQCydo
rjJiMEVChw3vs31/ENiF2kNSD5GsaykFtEXXZwB60bN6A74eTrJVFupGmjNR5Upx
zOhiOIdb7jz17yTx+vIoBd+3mPjlzS2LhFw/uWzs1LRztXBd7A/uvI83JL/c+4RN
QjfN8fxU4bJQldpl1U1DfuyLDYsUr8F0BaJbWta/uprVm8ZIIQIDAQABoyEwHzAd
BgNVHQ4EFgQUKqDj27xGyYQAuWBpnHs50DDsF90wDQYJKoZIhvcNAQELBQADggEB
ADGwK1dCoj646vH7o/cOGQlwtWeYfCpg3YZQNSYRsZlPhH04v+0inXpOjaMZJp12
tCkROu8p/f/suWHy6O/GbEmzdQL6z6SQbdti7mUXkV15nRIUURrAZYbOVUxtzDFE
GgG6B8BNRmxZfZqi1Vw5Hr3PQKFXVgFHkqLW9SihWtq99NM+B4WY5Az7GxYfgcAa
5xnnZKj+3HpOIoW3SFVrxli1AOEISy12BMbj0njEFDB5fca/jefiGQKjScXsdg3H
G2tWtLoKVhGmADl6hRIhIPKQwyFVA0YmC4mhkHDJ63xNbLDh+SXc0IdeJXUzbgW2
XP6dugjAyYzYHtIv5s438l8=
</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature></ns0:AuthnRequest>

you can find out that all the namesapces within output has been changed into ns0, ns1, ns2, etc...

**Comment by lwp007** [comment]
i have a raw xml file (c:\raw.xml) with the original content below:

<?xml version="1.0" encoding="UTF-8"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://test.com/abc" AttributeConsumingServiceIndex="0" ID="testid" IssueInstant="TEST" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">TEST</saml:Issuer><samlp:NameIDPolicy AllowCreate="False" /></samlp:AuthnRequest>

and after run with the code below:

keycontent = open( 'keys/private-key.pem', 'rt').read()
certcontent = open( 'keys/certificate.pem', 'rt').read()
f = open("C:/raw.xml","r")
lines = f.readlines()
root = ElementTree.fromstring(lines.pop())
signed_root = XMLSigner(method = signxml.methods.enveloped, signature_algorithm=u'rsa-sha1', digest_algorithm=u'sha1', c14n_algorithm=u'http://www.w3.org/2001/10/xml-exc-c14n#').sign(root, key=keycontent, passphrase='123456', cert=certcontent)
print ElementTree.tostring(signed_root)

i get this result:

<ns0:AuthnRequest xmlns:ns0="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:ns1="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:ns2="http://www.w3.org/2000/09/xmldsig#" AssertionConsumerServiceIndex="0" AssertionConsumerServiceURL="https://test.com/abc" AttributeConsumingServiceIndex="0" ID="testid" IssueInstant="TEST" ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"><ns1:Issuer>TEST</ns1:Issuer><ns0:NameIDPolicy AllowCreate="False" /><ns2:Signature><ns2:SignedInfo><ns2:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /><ns2:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><ns2:Reference URI="#testid"><ns2:Transforms><ns2:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><ns2:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" /></ns2:Transforms><ns2:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><ns2:DigestValue>x04GTDuVHS4Je+cdGGVHybck3iI=</ns2:DigestValue></ns2:Reference></ns2:SignedInfo><ns2:SignatureValue>...signvalues...</ns2:SignatureValue><ns2:KeyInfo><ns2:X509Data><ns2:X509Certificate>...x509cert...</ns2:X509Certificate></ns2:X509Data></ns2:KeyInfo></ns2:Signature></ns0:AuthnRequest>

you can find out all namespaces within the output have been changed into ns0, ns1, ns2, etc... 
is there a way i can keep the namespaces like samlp, saml in the raw xml? thanks a lot!
