### ISSUE TITLE
Signing and verifying a SOAP WS-Security envelope

### ISSUE THREAD

**Issue by tarikhagustia** [XML-Security/signxml#98]
can you give me an example for Signing and verifying a SOAP WS-Security envelope ? i see in your documentation page, still to  do

thanks

**Comment by mangcoding** [comment]
for verify ucan use this code: 
`XMLVerifier().verify(xml, x509_cert=cert).signature_xml`

but i still looking for how to sign because when i try to to sign and verified back always return false

**Comment by kislyuk** [comment]
Support for WS-Security is not currently being developed. It won't be developed unless someone steps up who wants to contribute patches, or a dedicated source of funding arises.
